/* One context, decoded buffers and permanent loop voices. No audio work in physics. */
const AudioManager={ctx:null,ready:new Map(),loops:new Map(),slots:[],fallback:new Map(),epoch:0,lastImpact:-Infinity,unlocked:false,stats:{decodes:0,loopSources:0,sfxSources:0,peakSfx:0,updates:0},
 enabled(){const s=Save.state.settings;return s.master!==false&&(s.engine!==false||s.drift!==false||s.effects!==false);},
 context(){if(this.ctx)return this.ctx;const C=window.AudioContext||window.webkitAudioContext;if(!C){this.legacy=true;return null;}try{this.ctx=new C({latencyHint:'interactive'});this.master=this.ctx.createGain();this.master.connect(this.ctx.destination);this.categories={};for(const k of ['ENGINE','DRIFT','SFX']){const g=this.ctx.createGain();g.connect(this.master);this.categories[k]=g;}for(let i=0;i<4;i++){const g=this.ctx.createGain();g.connect(this.categories.SFX);this.slots.push({gain:g,source:null});}return this.ctx;}catch(e){this.legacy=true;return null;}},
 unlock(){this.unlocked=true;if(!this.enabled())return;const c=this.context();if(c?.state==='suspended'&&!this.resuming){this.resuming=true;c.resume().catch(()=>{}).finally(()=>this.resuming=false);}},
 async buffer(name){if(!this.ready.has(name)){const task=fetch('assets/audio/'+name+'.mp3').then(r=>{if(!r.ok)throw Error('Audio '+name);return r.arrayBuffer();}).then(b=>this.ctx.decodeAudioData(b)).then(b=>{this.stats.decodes++;return b;});task.catch(()=>{});this.ready.set(name,task);}return this.ready.get(name);},
 async prepare(){if(!this.enabled())return;this.unlock();const c=this.context(),s=Save.state.settings,names=[...(s.engine!==false?['engine','idle']:[]),...(s.drift!==false?['tires']:[])];if(!c){for(const name of names)this.fallbackVoice(name);return;}await Promise.allSettled(names.map(async name=>{if(this.loops.has(name))return;try{const b=await this.buffer(name);if(this.loops.has(name))return;const source=c.createBufferSource(),gain=c.createGain();source.buffer=b;source.loop=true;gain.gain.value=0;source.connect(gain).connect(this.categories[name==='tires'?'DRIFT':'ENGINE']);source.start();this.loops.set(name,{source,gain,volume:0,rate:1});this.stats.loopSources++;}catch(e){this.fallbackVoice(name);}}));},
 fallbackVoice(name){if(!this.fallback.has(name)){const a=new Audio('assets/audio/'+name+'.mp3');a.loop=true;a.preload='auto';a.volume=0;this.fallback.set(name,a);}return this.fallback.get(name);},
 voice(name,volume,rate){const v=this.loops.get(name);if(v){const now=this.ctx.currentTime;if(Math.abs(volume-v.volume)>.002){v.gain.gain.setTargetAtTime(volume,now,.08);v.volume=volume;}if(Math.abs(rate-v.rate)>.01){v.source.playbackRate.setTargetAtTime(rate,now,.1);v.rate=rate;}return;}const a=this.fallback.get(name);if(!a)return;if(Math.abs(a.volume-volume)>.005)a.volume=volume;if(volume>0&&a.paused&&this.unlocked&&!a.starting){const epoch=this.epoch;a.starting=true;a.play().then(()=>{if(epoch!==this.epoch){a.pause();a.volume=0;}}).catch(()=>{}).finally(()=>a.starting=false);}},
 stop(){this.epoch++;for(const v of this.loops.values()){v.gain.gain.cancelScheduledValues(this.ctx.currentTime);v.gain.gain.setValueAtTime(0,this.ctx.currentTime);v.volume=0;}for(const a of this.fallback.values()){a.pause();a.volume=0;}for(const slot of this.slots)if(slot.source){slot.source.onended=null;try{slot.source.stop();}catch(e){}slot.source.disconnect();slot.source=null;}if(this.ctx?.state==='running')this.ctx.suspend().catch(()=>{});this.running=false;},
 update(){const s=Save.state.settings,on=gameRunning&&!gamePaused&&!document.hidden&&this.enabled();if(!on){if(this.running)this.stop();return;}if(!this.unlocked)return;if(!this.running){this.running=true;this.prepare();}this.stats.updates++;if(this.ctx?.state==='suspended')this.unlock();if(this.master)this.master.gain.value=s.master===false?0:1;const speed=Math.hypot(car.vx,car.vy),rpm=Math.min(1,speed/13+(keys.ArrowUp?.15:0));if(s.engine!==false){this.voice('idle',.14*(1-rpm),.9+rpm*.25);this.voice('engine',.18*rpm,.9+rpm*.45);}else{this.voice('idle',0,1);this.voice('engine',0,1);}let drift=0;if(s.drift!==false&&speed>Dynamics.driftSpeed){const angle=Math.abs(wrap(Math.atan2(car.vy,car.vx)-car.angle));if(angle>Dynamics.driftAngle*Math.PI/180)drift=Math.min(.32,.1+angle*.13);}this.voice('tires',drift,.94+Math.min(.13,speed*.004));},
 impact(){const s=Save.state.settings,now=performance.now();if(!gameRunning||gamePaused||s.master===false||s.effects===false||now-this.lastImpact<100||!this.unlocked)return;const c=this.context();if(!c)return;const slot=this.slots.find(v=>!v.source);if(!slot)return;this.lastImpact=now;if(!this.impactBuffer){const b=c.createBuffer(1,Math.ceil(c.sampleRate*.15),c.sampleRate),v=b.getChannelData(0);for(let i=0;i<v.length;i++){const t=i/c.sampleRate;v[i]=((t*65%1)*2-1)*Math.exp(-t*28)*.12;}this.impactBuffer=b;}const source=c.createBufferSource();source.buffer=this.impactBuffer;source.connect(slot.gain);slot.source=source;source.onended=()=>{source.disconnect();if(slot.source===source)slot.source=null;};source.start();this.stats.sfxSources++;this.stats.peakSfx=Math.max(this.stats.peakSfx,this.slots.filter(s=>s.source).length);},
 changed(){this.stop();if(Save.state.settings.master===false)AudioPlayer.music.pause();else if(AudioPlayer.requested)AudioPlayer.play();AudioPlayer.music.volume=Save.state.settings.master===false?0:Save.state.settings.volume;if(gameRunning&&!gamePaused)this.prepare();}
};
// Browser gesture unlock is registered once, never once per scene.
document.addEventListener('pointerdown',()=>AudioManager.unlock(),{passive:true});
document.addEventListener('keydown',()=>AudioManager.unlock(),{passive:true});
initAudio=()=>AudioManager.unlock();beep=()=>AudioManager.impact();
