const City={places:[],near:null,
 reset(){this.places=[];this.near=null;this.destination=null;if(selectedMode!=='city')return;
  for(const [name,x,y,action] of [['ШИНОМОНТАЖ',.355,.22,'tires'],['ГАРАЖ',.37,.49,'garage'],['АВТОСАЛОН',.82,.77,'dealer'],['LOUD SOUND',.77,.23,'audio'],['AR DRIVE',.22,.77,'install']]){const p=Traffic.route.filter(p=>this.places.every(q=>Math.hypot(p.x-q.x,p.y-q.y)>500)).reduce((best,p)=>!best||Math.hypot(p.x-x*W,p.y-y*H)<Math.hypot(best.x-x*W,best.y-y*H)?p:best,null);if(p)this.places.push({...p,name,action});}
 },
 update(){const button=this.button??=document.getElementById('serviceBtn');if(selectedMode!=='city')return;this.near=this.places.find(p=>Math.hypot(car.x-p.x,car.y-p.y)<220);button.hidden=!this.near||Math.hypot(car.vx,car.vy)>=1;if(this.near&&button.textContent!==this.near.name)button.textContent=this.near.name;button.onclick=()=>this.enter();},
 enter(){if(!this.near||Math.hypot(car.vx,car.vy)>=1)return;if(this.near.action==='garage')UI.garage(false);else if(this.near.action==='dealer')UI.garage(true);else if(['audio','install'].includes(this.near.action))this.audioShop(this.near.action);else Social.service();},
 audioShop(kind,inside=false){const install=kind==='install',root=UI.panel(install?'AR DRIVE':'LOUD SOUND');root.append(UI.el('img',{className:'business-art',src:'assets/social/'+(install?'ar-drive':inside?'loud-interior':'loud-exterior')+'.webp',alt:install?'Установочный центр AR DRIVE':inside?'Продавец LOUD SOUND':'Магазин LOUD SOUND'}));if(!inside){root.append(UI.el('button',{className:'primary',onclick:()=>this.audioShop(kind,true)},'ВОЙТИ'));return;}const a=Economy.audio();root.append(UI.el('p',{},Math.floor(Save.state.money)+' ₽ · '+a.level.toUpperCase()+' · '+(a.installed?'УСТАНОВЛЕНО':'НЕ УСТАНОВЛЕНО')));const buttons=UI.el('div',{className:'toolbar'});root.append(buttons);if(install){buttons.append(UI.el('button',{className:'primary',disabled:a.level==='none'||a.installed,onclick:()=>{const ok=Economy.installAudio();UI.toast(ok?'Аудиосистема установлена. Музыка доступна.':'Для установки нужно 10 000 ₽');this.audioShop(kind,true);}},a.installed?'УСТАНОВЛЕНО':'УСТАНОВИТЬ · 10 000 ₽'));if(a.level==='none')root.append(UI.el('p',{},'Сначала купи STANDARD или PRO в LOUD SOUND.'));}else{for(const level of ['standard','pro']){const price=level==='standard'?10000:a.level==='standard'?40000:50000;buttons.append(UI.el('button',{className:'primary',disabled:a.level===level||a.level==='pro',onclick:()=>{const ok=Economy.buyAudio(level);UI.toast(ok?(a.installed?'Уровень обновлён, повторная установка не нужна':'Покупка сохранена. Теперь в AR DRIVE за установкой.'):'Недостаточно денег');this.audioShop(kind,true);}},(level==='standard'?'КУПИТЬ СТАНДАРТ':'КУПИТЬ PRO')+' · '+price.toLocaleString('ru')+' ₽'));}root.append(UI.el('p',{},'STANDARD: 20 случайных треков. PRO: весь каталог. Апгрейд STANDARD → PRO: 40 000 ₽. Установка переносится на выбранную машину без повторной оплаты.'));}buttons.append(UI.el('button',{onclick:()=>UI.closePanel()},'ВЫЙТИ'));},
 draw(g){if(selectedMode!=='city')return;for(const p of this.places){g.save();g.translate(p.x,p.y);g.strokeStyle=this.destination===p?'#ffda42':'#f1e7c8';g.lineWidth=4;g.strokeRect(-65,-90,130,180);g.font='bold 27px monospace';g.textAlign='center';g.fillStyle='#f1e7c8';g.fillText(p.name,0,-115);g.restore();}}
};
