/* Local test hooks. Client-side code gate hides tools, not a security boundary. */
const DevMode={active:false,debug:false,
 hash(text){let h=2166136261;for(const c of text)h=Math.imul(h^c.charCodeAt(0),16777619);return h>>>0;},
 unlock(code){if(this.hash(String(code).trim())!==364975005)return false;this.active=true;return true;},
 gate(root){const row=UI.el('p'),toggle=UI.el('input',{type:'checkbox',checked:this.active}),entry=UI.el('div',{className:'hidden'});row.append(toggle,document.createTextNode(' РЕЖИМ РАЗРАБОТЧИКА'));root.append(row,entry);toggle.onchange=()=>{if(!toggle.checked){this.active=false;this.debug=false;entry.className='hidden';return;}if(this.active){this.open();return;}entry.className='';entry.innerHTML='';const code=UI.el('input',{type:'password',inputMode:'numeric',placeholder:'Введите код разработчика',autocomplete:'off'});entry.append(code,UI.el('button',{onclick:()=>{if(this.unlock(code.value)){code.value='';this.open();}else{code.value='';toggle.checked=false;entry.className='hidden';}}},'ОТКРЫТЬ'));};if(this.active)root.append(UI.el('button',{onclick:()=>this.open()},'ИНСТРУМЕНТЫ РАЗРАБОТЧИКА'));},
 grant(){if(!this.active)return;const s=Save.state;s.money+=1000000;s.total=Math.max(s.total,3000000);s.owned=CATALOG.cars.map(c=>c.id);s.achievements=[...new Set([...s.achievements,...Achievements.map(a=>a.id)])];for(const c of CATALOG.cars){const expanded=['baseline','rare','silvia'].includes(c.id);s.custom[c.id]={paint:0,rims:0,aero:0,paid:[...Array.from({length:expanded?3:1},(_,i)=>'paint'+(i+1)),...Array.from({length:expanded?3:1},(_,i)=>'rims'+(i+1)),'aero1']};}s.social.outfits=Social.outfits.map((_,i)=>i);s.social.followers=Math.max(5000,s.social.followers);s.audioSystem={level:'pro',installed:true,tracks:CATALOG.music.map((_,i)=>i)};s.impound={};s.tires=100;Save.persist();UI.toast('Контент куплен, +1 000 000 ₽. Все существующие трассы и режимы доступны.');},
 spawn(id,person=false){if(!this.active||!gameRunning)return;if(person){const p=Social.people[id];if(!p)return;const n=Traffic.create(p.car,NpcReplay.nearest(car)+carH()*4,p.portrait);if(n){Object.assign(n,{person:id,special:true,kind:gameType==='legal'?'drifter':'traffic',profile:'pro',leaveAfter:4,travelled:0});World.npcs.push(n);}}else{if(!CATALOG.cars.some(c=>c.id===id))return;Save.state.selected=id;if(!Save.state.owned.includes(id))Save.state.owned.push(id);Save.persist();resetCar();}UI.closePanel();},
 async testClip(){if(!this.active||!gameRunning||!NpcReplay.gates)return;const bucket=NpcReplay.bucket(),serial=NpcReplay.loadSerial,wasEnabled=NpcReplay.enabled;NpcReplay.enabled=false;const n=Traffic.create('gocha',NpcReplay.gates.startDistance,0),frames=[];if(!n){NpcReplay.enabled=wasEnabled;return;}Object.assign(n,{kind:'drifter',profile:'pro',travelled:0});let done=false,ticks=0;const oldCar={x:car.x,y:car.y},oldNpcs=World.npcs;World.npcs=[];car.x=car.y=-10000;n.behavior='drift';n.behaviorAt=Infinity;try{for(;ticks<18000;ticks++){if(serial!==NpcReplay.loadSerial)throw Error('Трасса изменилась');const before={x:n.x,y:n.y};if(gameType==='illegal')Traffic.update(n);else Traffic.drive(n);if(ticks%4===0)frames.push(ticks/60,n.x,n.y,n.angle,n.vx,n.vy,n.steer||0,1,0,0,n.drift||0,wrap(n.angle-Math.atan2(n.vy,n.vx)));if(ticks>360&&NpcReplay.crossed(NpcReplay.gates.finish,before,n)){done=true;break;}if(ticks%600===0)await new Promise(resolve=>setTimeout(resolve,0));}if(!done)throw Error('AI не завершил тестовый участок');if(frames[frames.length-12]!==ticks/60)frames.push(ticks/60,n.x,n.y,n.angle,n.vx,n.vy,n.steer||0,1,0,0,n.drift||0,wrap(n.angle-Math.atan2(n.vy,n.vx)));const clip={id:crypto.randomUUID(),version:1,bucket,track:selectedMapId,direction:gameType==='legal'?Tracks.direction:'forward',date:Date.now(),duration:ticks/60,car:'gocha',stride:12,frames:new Float32Array(frames),test:true};if(!NpcReplay.validClip(clip,bucket)||!NpcReplay.safeFrames(clip.frames))throw Error('Тестовая траектория AI небезопасна. Запишите заезд игрока на этой трассе.');await Save.npcPut(clip);NpcReplay.clips.push(clip);NpcReplay.clips=NpcReplay.clips.slice(-6);UI.toast('Тестовая AI-запись создана и помечена TEST');}catch(e){UI.toast(e.message);}finally{NpcReplay.enabled=wasEnabled;if(serial===NpcReplay.loadSerial){Object.assign(car,oldCar);World.npcs=oldNpcs;}}},
 open(){if(!this.active)return;const root=UI.panel('РАЗРАБОТЧИК'),add=(text,fn)=>root.append(UI.el('button',{onclick:()=>{if(this.active)fn();}},text));add('ОТКРЫТЬ И КУПИТЬ ВЕСЬ КОНТЕНТ',()=>this.grant());add('+100 000 ₽',()=>{Save.state.money+=100000;Save.persist();UI.toast('+100 000 ₽');});
 const select=(title,items)=>{root.append(UI.el('p',{},title));const el=UI.el('select',{ariaLabel:title});for(const [value,label] of items)el.append(UI.el('option',{value},label));root.append(el);return el;};
 const cars=select('Машина игрока',CATALOG.cars.map(c=>[c.id,c.name]));add('ВЫЗВАТЬ МАШИНУ',()=>this.spawn(cars.value));add('СОЗДАТЬ NPC НА ВЫБРАННОЙ МАШИНЕ',()=>{if(!gameRunning)return;const n=Traffic.create(cars.value,NpcReplay.nearest(car)+carH()*4,0);if(n){Object.assign(n,{kind:gameType==='legal'?'drifter':'traffic',profile:'advanced',leaveAfter:4,travelled:0});World.npcs.push(n);UI.closePanel();}});const people=select('NPC / персонаж',Object.entries(Social.people).map(([id,p])=>[id,p.name+' · '+p.car]));add('ВЫЗВАТЬ NPC',()=>this.spawn(people.value,true));add('ВЫЗВАТЬ ПЕРСОНАЖА',()=>{const p=Social.people[people.value];UI.dialog(Social.portrait(people.value),p.name+': тест персонажа.',[['ЗАКРЫТЬ',()=>{}]]);});
 const character=select('Персонаж',CATALOG.characters.map((name,i)=>[String(i),name]));add('ПОКАЗАТЬ ПЕРСОНАЖА',()=>UI.dialog(Number(character.value),CATALOG.characters[Number(character.value)],[['ЗАКРЫТЬ',()=>{}]]));
 const track=select('Трасса',Object.entries(MAPS).map(([id,t])=>[id,t.name]));const mode=select('Режим',[['training','Тренировка'],['competition','Соревнование'],['illegal','Нелегал'],['city','Город']]);add('ЗАПУСТИТЬ ТРАССУ',()=>{const m=mode.value,t=MAPS[track.value];if(['training','competition'].includes(m)&&t.mode!=='legal'){UI.toast('Для этого режима выбери легальную трассу');return;}if(m==='city'){Game.start('wheel','city');return;}if(m==='illegal'&&t.mode==='legal'){UI.toast('Выбери нелегальную трассу');return;}Game.start(track.value,m);});
 const rival=select('Парный соперник',['gocha','tsar','borsh','hustler'].map(id=>[id,Social.people[id].name]));add('ПАРНЫЙ ЗАЕЗД',()=>{if(MAPS[track.value].mode!=='legal'){UI.toast('Выбери легальную трассу');return;}Save.state.social.followers=Math.max(5000,Save.state.social.followers);Tandem.start(rival.value,track.value);});
 add('NPC REPLAY: '+(NpcReplay.enabled?'ON':'OFF'),()=>{NpcReplay.enabled=!NpcReplay.enabled;for(const n of World.npcs)n.replay=null;this.open();});add('ОБЫЧНЫЙ AI',()=>{NpcReplay.enabled=false;for(const n of World.npcs)n.replay=null;this.open();});add('DEBUG: '+(this.debug?'ON':'OFF'),()=>{this.debug=!this.debug;FrameMetrics.reset();this.open();});
 root.append(UI.el('h2',{},'REPLAY · '+selectedMapId+' · '+NpcReplay.clips.length));for(const clip of NpcReplay.clips)root.append(UI.el('p',{},(clip.test?'TEST · ':'')+clip.id.slice(0,8)+' · '+clip.duration.toFixed(1)+' с · '+clip.frames.length/12+' точек'));add('СОЗДАТЬ ТЕСТОВЫЙ REPLAY',async()=>{await this.testClip();if(this.active)this.open();});add('ОЧИСТИТЬ REPLAY ЭТОЙ ТРАССЫ',()=>UI.dialog(6,'Удалить записи NPC только текущей трассы и направления?',[['УДАЛИТЬ',async()=>{await NpcReplay.clear();if(this.active)this.open();}],['ОТМЕНА',()=>this.open()]]));root.append(UI.el('p',{className:'muted'},'Записи содержат 15 точек/с. TEST — траектория существующего AI, не заезд игрока.'));add('ВЫКЛЮЧИТЬ DEVELOPER MODE',()=>{this.active=this.debug=false;UI.settings();});},
 update(){let box=document.getElementById('replayDebug');if(!this.active||!this.debug||!gameRunning){if(box)box.hidden=true;return;}if(!box){box=UI.el('pre',{id:'replayDebug',className:'replay-debug'});document.body.append(box);}box.hidden=false;const g=NpcReplay.gates;box.textContent=selectedMapId+' · записей '+NpcReplay.clips.length+' · '+NpcReplay.reason+'\n'+World.npcs.map((n,i)=>{const r=n.replay;return i+': '+(r?r.clip.id.slice(0,6)+' '+r.time.toFixed(1)+'с '+Math.round(r.time/r.clip.duration*100)+'%':'AI');}).join('\n')+(g?'\nSTART '+Math.round(g.start.cx)+','+Math.round(g.start.cy)+' FINISH '+Math.round(g.finish.cx)+','+Math.round(g.finish.cy):'')+'\nFPS '+FrameMetrics.fps.toFixed(1)+' PHYS '+FrameMetrics.physicsMs.toFixed(2)+'ms DRAW '+FrameMetrics.renderMs.toFixed(2)+'ms MAX '+FrameMetrics.maxFrameMs.toFixed(1)+'ms\nAUDIO '+JSON.stringify(AudioManager.stats);}
};
window.DevMode=DevMode;
const normalSettings=UI.settings.bind(UI);UI.settings=function(){normalSettings();DevMode.gate(document.querySelector('#rmPanel .panel-shell'));};
const normalUnlock=Economy.unlocked.bind(Economy);Economy.unlocked=c=>DevMode.active||normalUnlock(c);
