/* Compact 15 Hz driving clips; existing AI remains the connector and fallback. */
const NpcReplay={stride:12,clips:[],enabled:true,record:null,last:null,tick:0,sequence:0,gates:null,loadSerial:0,reason:'',
 bucket(){return selectedMapId+':'+(gameType==='legal'?Tracks.direction:'forward');},
 nearest(p){let best=Infinity,at=0;for(let d=0;d<Traffic.length;d+=25){const q=Traffic.point(d),v=(q.x-p.x)**2+(q.y-p.y)**2;if(v<best){best=v;at=d;}}return at;},
 async load(){const serial=++this.loadSerial;this.record=null;this.last={x:car.x,y:car.y};this.tick=0;this.clips=[];this.reason='';Traffic.build();if(!Traffic.length){this.gates=null;return;}const legal=gameType==='legal'&&markers.lines[0]&&markers.lines[1];const start=legal?{x:markers.lines[0].cx,y:markers.lines[0].cy}:Traffic.point(Traffic.length*.05),finish=legal?{x:markers.lines[1].cx,y:markers.lines[1].cy}:Traffic.point(Traffic.length*.75),sd=this.nearest(start),fd=this.nearest(finish),length=(fd-sd+Traffic.length)%Traffic.length;
 const gate=(p,d)=>{const a=Traffic.point(d+60),b=Traffic.point(d-60),angle=Math.atan2(a.y-b.y,a.x-b.x),w=carH()*1.35;return{x:p.x-Math.sin(angle)*w,y:p.y+Math.cos(angle)*w,w:Math.sin(angle)*w*2,h:-Math.cos(angle)*w*2,cx:p.x,cy:p.y,angle};};
 this.gates={start:legal?{...markers.lines[0],angle:gate(start,sd).angle}:gate(start,sd),finish:legal?{...markers.lines[1],angle:gate(finish,fd).angle}:gate(finish,fd),startDistance:sd,finishDistance:fd,length,checkpoints:Array.from({length:8},(_,i)=>Traffic.point(sd+length*(i+1)/9))};const bucket=this.bucket();try{const clips=await Save.npcList(bucket);if(serial===this.loadSerial)this.clips=clips.filter(c=>this.validClip(c,bucket));}catch(e){this.reason='Хранилище replay недоступно';}
 },
 validClip(c,bucket=this.bucket()){if(c.version!==1||c.bucket!==bucket||c.track!==selectedMapId||!c.frames||c.frames.length<this.stride*90||c.frames.length>this.stride*4502||c.frames.length%this.stride||c.duration<6||c.duration>300)return false;for(let i=0;i<c.frames.length;i+=this.stride){for(let j=0;j<this.stride;j++)if(!Number.isFinite(c.frames[i+j]))return false;if(c.frames[i]<0||i&&c.frames[i]<=c.frames[i-this.stride]||c.frames[i+1]<0||c.frames[i+1]>W||c.frames[i+2]<0||c.frames[i+2]>H)return false;}return Math.abs(c.frames[c.frames.length-this.stride]-c.duration)<.02;},
 crossed(g,a,b){return lineTouched(g,a.x,a.y,b.x,b.y)&&(b.x-a.x)*Math.cos(g.angle)+(b.y-a.y)*Math.sin(g.angle)>0;},
 begin(){this.record={bucket:this.bucket(),track:selectedMapId,direction:gameType==='legal'?Tracks.direction:'forward',frames:[],ticks:0,still:0,off:0,checkpoint:0,distance:0,driftTicks:0,startHits:Replay.hits,anchor:{x:car.x,y:car.y},anchorTicks:0};this.reason='Запись';this.capture();},
 capture(){const r=this.record;if(r.frames.length&&r.frames[r.frames.length-this.stride]===r.ticks/60)return;const speed=Math.hypot(car.vx,car.vy),slip=speed>.1?wrap(car.angle-Math.atan2(car.vy,car.vx)):0;const previous=r.frames.length-this.stride;if(!this.safePose(car.x,car.y,car.angle))r.unsafe=true;if(previous>=0){const ax=r.frames[previous+1],ay=r.frames[previous+2],aa=r.frames[previous+3],steps=Math.ceil(Math.hypot(car.x-ax,car.y-ay)/3);for(let i=1;i<steps;i++){const t=i/steps;if(!this.safePose(ax+(car.x-ax)*t,ay+(car.y-ay)*t,aa+wrap(car.angle-aa)*t)){r.unsafe=true;break;}}}r.frames.push(r.ticks/60,car.x,car.y,car.angle,car.vx,car.vy,car.steer||0,keys.ArrowUp?1:0,keys.ArrowDown?1:0,keys[' ']?1:0,car.drift||0,slip);},
 reject(reason){this.record=null;this.reason=reason;},
 sample(){if(!gameRunning||gamePaused||Tandem.active||!this.gates)return;const previous=this.last||car;this.last={x:car.x,y:car.y};this.tick++;if(!this.record){if(this.crossed(this.gates.start,previous,car))this.begin();return;}const r=this.record,step=Math.hypot(car.x-previous.x,car.y-previous.y),speed=Math.hypot(car.vx,car.vy);r.ticks++;r.distance+=step;if(![car.x,car.y,car.angle,car.vx,car.vy].every(Number.isFinite)){this.reject('Некорректные координаты');return;}if(step>Math.max(18,Dynamics.maximum(Vehicles.current().stats,11)*2.2)){this.reject('Скачок координат');return;}r.still=speed<.4?r.still+1:0;const surface=carSurfaceInfo();r.off=surface.wallRatio>0||surface.shoulderRatio>.8?r.off+1:0;if(r.still>180||r.off>90||r.ticks>18000||comp?.invalid||Replay.hits-r.startHits>3){this.reject('Невалидный заезд');return;}
 if(Math.hypot(car.x-r.anchor.x,car.y-r.anchor.y)>carH()*2){r.anchor={x:car.x,y:car.y};r.anchorTicks=0;}else if(++r.anchorTicks>480){this.reject('Застревание');return;}
 if(speed>3&&Math.abs(wrap(car.angle-Math.atan2(car.vy,car.vx)))>.2)r.driftTicks++;
 const cp=this.gates.checkpoints[r.checkpoint];if(cp&&Math.hypot(car.x-cp.x,car.y-cp.y)<Math.max(180,carH()*2))r.checkpoint++;
 if(r.ticks%4===0)this.capture();if(this.crossed(this.gates.finish,previous,car))this.finish();},
 async finish(){const r=this.record;if(!r)return false;this.capture();this.record=null;if(r.ticks<360||r.checkpoint<7||r.distance<this.gates.length*.65||r.driftTicks<30||comp?.invalid){this.reason='Заезд не прошёл проверку';return false;}if(r.unsafe){this.reason='Небезопасная траектория';return false;}const clip={id:crypto.randomUUID(),version:1,bucket:r.bucket,track:r.track,direction:r.direction,date:Date.now(),duration:r.ticks/60,car:Save.state.selected,stride:this.stride,frames:new Float32Array(r.frames),test:false};try{await Save.npcPut(clip);if(this.bucket()===r.bucket){this.clips.push(clip);this.clips=this.clips.slice(-6);}this.reason='Заезд сохранён для NPC';return true;}catch(e){this.reason='Не удалось сохранить replay';return false;}},
 eligible(n){return this.enabled&&this.gates&&this.clips.length&&!(n.replayCooldown>World.frame)&&!n.pitting&&!(n.retaliateUntil>World.frame)&&['drifter','traffic'].includes(n.kind);},
 alignDistance(n){const d=this.nearest(n),cycle=Math.floor((n.distance||0)/Traffic.length);n.distance=cycle*Traffic.length+d;},
 safeFrames(frames){for(let i=0;i<frames.length;i+=this.stride){if(!this.safePose(frames[i+1],frames[i+2],frames[i+3]))return false;if(i){const a=i-this.stride,dx=frames[i+1]-frames[a+1],dy=frames[i+2]-frames[a+2],steps=Math.max(1,Math.ceil(Math.hypot(dx,dy)/3));for(let n=1;n<steps;n++){const t=n/steps;if(!this.safePose(frames[a+1]+dx*t,frames[a+2]+dy*t,frames[a+3]+wrap(frames[i+3]-frames[a+3])*t))return false;}}}return true;},
 safePose(x,y,a){const h=carH()*.4,w=carW()*.4,c=Math.cos(a),s=Math.sin(a);return [[0,0],[h,0],[-h,0],[0,w],[0,-w],[h,w],[h,-w],[-h,w],[-h,-w]].every(([dx,dy])=>surfaceAt(x+c*dx-s*dy,y+s*dx+c*dy)!=='wall');},
 drive(n,dt=1){if(!this.eligible(n)){n.replay=null;return false;}if(!n.replay){n.replayChoice=(n.replayChoice??this.sequence++)%this.clips.length;const clip=this.clips[n.replayChoice],f=clip.frames,dist=Math.hypot(n.x-f[1],n.y-f[2]);if(n.replayExit){if(Math.hypot(n.x-this.gates.finish.cx,n.y-this.gates.finish.cy)>carH()*3)n.replayExit=false;return false;}if(dist>carH()*1.3)return false;
 if(dist>12){Traffic.drive(n,{target:{x:f[1],y:f[2]},speed:Math.min(3,dist*.12),slip:0});return true;}
 if(Math.abs(wrap(n.angle-f[3]))>.5)return false;n.replay={clip,time:0,index:0,offsetX:n.x-f[1],offsetY:n.y-f[2],angleOffset:wrap(n.angle-f[3]),held:0};}
 for(let step=0;step<dt;step++){const r=n.replay;if(!r)break;const f=r.clip.frames,S=this.stride,t=Math.min(r.clip.duration,r.time+1/60);while(r.index+S*2<f.length&&f[r.index+S]<t)r.index+=S;const a=r.index,b=Math.min(a+S,f.length-S),q=b===a?0:Math.max(0,Math.min(1,(t-f[a])/(f[b]-f[a]||1))),fade=Math.max(0,1-t),x=f[a+1]+(f[b+1]-f[a+1])*q+r.offsetX*fade,y=f[a+2]+(f[b+2]-f[a+2])*q+r.offsetY*fade,angle=f[a+3]+wrap(f[b+3]-f[a+3])*q+r.angleOffset*fade,dist=Math.hypot(x-n.x,y-n.y);let safe=dist<18;
 for(let at=1;safe&&at<=Math.max(1,Math.ceil(dist/3));at++){const z=at/Math.max(1,Math.ceil(dist/3));safe=this.safePose(n.x+(x-n.x)*z,n.y+(y-n.y)*z,n.angle+wrap(angle-n.angle)*z);}
 const pose={x,y,angle};if(safe&&[car,...World.npcs].some(o=>o!==n&&World.contact(pose,o)))safe=false;
 if(!safe){n.vx=n.vy=0;if(++r.held>120){n.lastReplayEnd='blocked';n.replayCooldown=World.frame+300;n.replay=null;n.replayExit=true;this.alignDistance(n);}return true;}
 r.held=0;n.vx=(x-n.x);n.vy=(y-n.y);n.x=x;n.y=y;n.angle=angle;n.steer=f[a+6];n.throttle=f[a+7];n.brake=!!f[a+8];n.handbrake=!!f[a+9];n.drift=f[a+10];n.lateral=-n.vx*Math.sin(angle)+n.vy*Math.cos(angle);const projection=Traffic.project(n),delta=Math.max(0,Math.min(dist*1.5+.5,projection.distance-n.distance));n.distance+=delta;n.travelled=(n.travelled||0)+delta;r.time=t;
 if(t>=r.clip.duration){n.lastReplayEnd='finished';n.replay=null;n.replayExit=true;n.replayChoice=(n.replayChoice+1)%this.clips.length;this.alignDistance(n);}
 }return true;},
 async clear(){await Save.npcClear(this.bucket());this.clips=[];for(const n of World.npcs)n.replay=null;this.reason='Записи трассы удалены';},
 debugDraw(g){if(!window.DevMode?.active||!DevMode.debug||!this.gates)return;g.save();g.lineWidth=5;for(const [name,p] of [['START',this.gates.start],['FINISH',this.gates.finish]]){g.strokeStyle='#ff53ea';g.beginPath();g.moveTo(p.x,p.y);g.lineTo(p.x+p.w,p.y+p.h);g.stroke();g.fillStyle='#ff53ea';g.font='24px monospace';g.fillText(name,p.cx,p.cy);}g.restore();}
};
