const Replay={frames:[],tick:0,enabled:true,headStart:60,ghostClock:0,contactCooldown:0,ghost:null,ghostFrame:null,pending:null,active:false,hits:0,turn:0,lastAngle:0,
 reset(){this.ghostClock=0;this.contactCooldown=0;this.frames=[];this.tick=0;this.pending=null;this.ghostFrame=this.ghost?.frames?.length?{x:this.ghost.frames[0][0],y:this.ghost.frames[0][1],angle:this.ghost.frames[0][2],vx:0,vy:0}:null;this.active=false;this.hits=0;this.turn=0;this.lastAngle=car.angle;document.getElementById('saveRun')?.remove();},
 sample(){if(gamePaused||!car||selectedMode!=='competition')return;this.tick++;const active=selectedMode==='competition'?comp?.startCrossed:true;if(active){this.active=true;this.frames.push([+car.x.toFixed(3),+car.y.toFixed(3),+car.angle.toFixed(5),+car.vx.toFixed(4),+car.vy.toFixed(4)]);}
  if(this.frames.length>108000){UI.toast('Достигнут лимит записи: 30 минут');if(comp)invalidateCompetition('ЛИМИТ ЗАЕЗДА: 30 МИНУТ');else this.finishTraining();return;}
  if(this.contactCooldown>0)this.contactCooldown--;if(this.ghost){this.ghostClock=active?this.headStart+this.frames.length-1:Math.min(this.headStart,this.ghostClock+1);const f=this.ghost.frames[this.ghostClock];this.ghostFrame=f?{x:f[0],y:f[1],angle:f[2],vx:f[3],vy:f[4]}:null;
   if(this.enabled&&this.ghostFrame&&active&&!this.contactCooldown&&World.contact(car,this.ghostFrame)){this.contactCooldown=60; /* Visual ghost: no impulse, penalty, or run invalidation. */}
  }
 },
 prepare(){if(selectedMode!=='competition'||!comp||comp.invalid||this.pending||!this.frames.length)return;const score=comp?comp.score:Math.floor(trainingScore);this.pending={id:globalThis.crypto?.randomUUID?.()||Date.now().toString(36)+'-'+Math.random().toString(36).slice(2),track:selectedMapId,direction:Tracks.direction,mode:selectedMode,score,drift:Math.floor(trainingScore),elapsed:this.frames.length/60,date:Date.now(),car:Save.state.selected,custom:{...Save.state.custom[Save.state.selected]},frames:this.frames.slice(),collisions:this.hits,angle:comp?.angle||0,line:comp?.clipping||0,style:comp?.style||0};
  const socialEvent=Social.run(score,true);const s=Save.state;s.runs++;if(this.hits===0)s.clean++;if(comp){s.money+=score*15;s.respect+=score;for(const q of comp.clippingQuality.values())if(q>=.9)s.perfect++;}Economy.check();
  this.pending.nick=localStorage.getItem('raremasters.nick')||'DRIVER';Save.put(this.pending).catch(e=>UI.toast('Автосохранение повтора не удалось: '+e.message));
  const box=document.createElement('div');box.id='saveRun';const label=document.createElement('label');label.textContent='НИК ';const input=document.createElement('input');input.maxLength=20;input.value=localStorage.getItem('raremasters.nick')||'DRIVER';input.id='nickname';label.append(input);box.append(label);const b=document.createElement('button');b.textContent='СОХРАНИТЬ РЕЗУЛЬТАТ И GHOST';b.onclick=async()=>{b.disabled=true;try{const nick=input.value.trim().slice(0,20)||'DRIVER';await Save.put({...this.pending,nick});localStorage.setItem('raremasters.nick',nick);const list=await Save.list(selectedMapId,Tracks.direction,selectedMode);b.textContent=`СОХРАНЕНО · МЕСТО ${list.findIndex(r=>r.id===this.pending.id)+1}`;}catch(e){b.disabled=false;b.textContent='ПОВТОРИТЬ СОХРАНЕНИЕ';UI.toast('Ошибка сохранения ghost: '+e.message);}};box.append(b);if(socialEvent)box.append(UI.el('button',{onclick:()=>{if(Social.publish(socialEvent.id))UI.toast('Видео опубликовано');}},'ВЫЛОЖИТЬ В ДОЛБОГРАММ'));document.getElementById('resultStats').after(box);
 },
 finishTraining(){if(!gameRunning||gamePaused||comp)return;gamePaused=true;document.getElementById('resultScore').textContent=Math.floor(trainingScore);document.getElementById('resultStats').textContent=`DRIFT · ${(this.frames.length/60).toFixed(1)} сек. · ${this.hits} контактов`;showScreen('result');this.prepare();},
 draw(g){if(!this.enabled||!this.ghostFrame)return;const d=CATALOG.cars.find(c=>c.id===this.ghost.car)||CATALOG.cars[0];Vehicles.drawVehicle(g,this.ghostFrame,d,this.ghost.custom);g.fillStyle='#f3c850';g.font='bold 28px monospace';g.fillText(this.ghost.leaderName||'GHOST',this.ghostFrame.x-40,this.ghostFrame.y-90);}
};

Replay.enabled=Save.state.settings.ghost!==false;

