/* Local in-world social progression. Stores event metadata, never full video files. */
const Social={
 people:{borsh:{name:'Борщ',car:'borsh',portrait:4,followers:100,art:'borsh-silvia'},subaru:{name:'Борщ',car:'subaru',portrait:4,followers:100,art:'borsh-subaru'},hustler:{name:'Виталя Хаслер',car:'hustler',portrait:2,followers:250,art:'hustler'},artak:{name:'Артак',car:'artak',portrait:0,followers:400},osman:{name:'Осман',car:'mercedes',portrait:5,followers:500},rare:{name:'Ваня RAREMASTERS',car:'rare',portrait:1,followers:0},grey:{name:'Серый',car:'bmw',portrait:6,followers:0},gocha:{name:'Гоча',car:'gocha',portrait:0,followers:3000},tsar:{name:'Царь',car:'tsar',portrait:0,followers:5000}},
 portrait(id){const p=this.people[id];return ['artak','osman','gocha','tsar'].includes(id)?{name:p.name,image:'assets/social/'+id+'.webp'}:p.portrait;},
 outfits:[{name:'Оригинал',price:0},{name:'Бордовый бомбер',price:3500},{name:'Синий комплект',price:5500},{name:'Utility: куртка, карго и цепь',price:8500}],
 images:new Map(),
 init(){const s=Save.state.social;s.following??=['rare','wheeldoctors'];s.liked??=[];s.jobs??={};s.lastRide??={};s.likes??=0;s.views??=0;s.drafts??=[];s.posted??=[];s.outfits??=[0];s.outfit??=0;s.lastPhoto??=0;s.lastPost??=0;s.relations??={};s.attentionAt??=Date.now();this.decay();},
 decay(){const s=Save.state.social,minutes=Math.max(0,(Date.now()-s.attentionAt)/60000);s.attention=Math.max(0,s.attention-minutes*.08);s.attentionAt=Date.now();},
 image(src){if(!this.images.has(src)){const im=new Image();im.src=src;this.images.set(src,im);}return this.images.get(src);},
 snapshot(){return{car:Save.state.selected,custom:{...Save.state.custom[Save.state.selected]},outfit:Save.state.social.outfit,track:selectedMapId};},
 draft(kind,quality,extra={}){const s=Save.state.social;const event={id:globalThis.crypto?.randomUUID?.()||Date.now().toString(36)+'-'+Math.random().toString(36).slice(2),kind,quality:Math.max(1,Math.min(100,quality)),date:Date.now(),illegal:selectedMode==='illegal',...this.snapshot(),...extra};s.drafts.unshift(event);s.drafts=s.drafts.slice(0,8);Save.persist();return event;},
 run(score,competition=false){if(competition&&score>=60&&Replay.hits===0)for(const job of Object.values(Save.state.social.jobs))if(job.state==='active')job.state='done';if(score<(competition?15:1000))return null;return this.draft('video',competition?score:Math.min(80,score/500),{competition,caption:competition?'Результат соревнования: '+Math.round(score):'Уличная сессия: '+Math.floor(score)+' DRIFT',winner:competition&&score>=90});},
 publish(id){const s=Save.state.social,event=s.drafts.find(p=>p.id===id);if(!event||s.posted.includes(id))return false;if(Date.now()-s.lastPost<60000){UI.toast('Следующая публикация через '+Math.ceil((60000-(Date.now()-s.lastPost))/1000)+' с');return false;}
  this.decay();const gain=Math.round(3+event.quality*.32+(event.person?12:0)+(event.winner?20:0));event.followers=gain;event.views=gain*17+Math.floor(event.quality*4);event.likes=Math.round(event.views*.12);s.followers+=gain;s.views+=event.views;s.likes+=event.likes;s.attention=Math.min(100,s.attention+(event.illegal?3+event.quality*.08:0));s.posts.unshift(event);s.posts=s.posts.slice(0,30);s.posted.unshift(id);s.posted=s.posted.slice(0,100);s.drafts=s.drafts.filter(p=>p.id!==id);s.lastPost=Date.now();
  Save.state.money+=Math.min(500,Math.floor(gain*(1+Math.min(3,s.followers/2000))));if(event.person){const person=event.person==='subaru'?'borsh':event.person;s.relations[person]=(s.relations[person]||0)+1;}Economy.check();UI.toast('ДОЛБОГРАММ +'+gain+' подписчиков');return true;
 },
 offer(event){if(!event)return;UI.dialog(6,'Заезд завершён. Выложить видео в Долбограмм? Нелегальная публикация повышает внимание полиции.',[['ВЫЛОЖИТЬ',()=>{this.publish(event.id);}],['НЕ СЕЙЧАС',()=>{UI.toast('Черновик сохранён в Долбограмме');}]]);},
 photo(){if(!gameRunning||Math.hypot(car.vx,car.vy)>1){UI.toast('Остановись для фотографии');return;}const s=Save.state.social;if(Date.now()-s.lastPhoto<60000){UI.toast('Новый кадр будет доступен через минуту');return;}
  const npc=World.npcs.find(n=>n.special&&Math.hypot(n.x-car.x,n.y-car.y)<280),person=npc?.person||npc?.car.id,info=this.people[person];
  if(info&&s.followers<info.followers){UI.dialog(this.portrait(person),info.name+': сначала набери '+info.followers+' подписчиков — потом совместный кадр.',[['ПОНЯЛ',()=>{}]]);return;}
  if(info&&(s.relations[person==='subaru'?'borsh':person]||0)>0){this.meet(person,npc);return;}s.lastPhoto=Date.now();const event=this.draft('photo',info?50:15,{person:info?person:null,illegal:false,caption:info?'Встреча: '+info.name:'Моя '+Vehicles.current().name});this.offerPhoto(event);
 },
 meet(id,npc){const s=Save.state.social,info=this.people[id],job=s.jobs[id];const buttons=[['СОВМЕСТНОЕ ФОТО',()=>{s.lastPhoto=Date.now();this.offerPhoto(this.draft('photo',50,{person:id,illegal:false,caption:'Встреча: '+info.name}));}]];if(!job)buttons.push(['ВЗЯТЬ ЗАДАНИЕ',()=>{s.jobs[id]={state:'active'};Save.persist();UI.toast(info.name+': пройди соревнование без контактов на 60+ баллов');}]);else if(job.state==='done')buttons.push(['ЗАБРАТЬ НАГРАДУ · 1500 ₽',()=>{job.state='claimed';Save.state.money+=1500;s.relations[id]=(s.relations[id]||0)+1;Save.persist();UI.toast('Задание выполнено · +1500 ₽');}]);if((s.relations[id]||0)>=2&&Date.now()-(s.lastRide[id]||0)>=600000)buttons.push(['ПОКАТАТЬСЯ ВМЕСТЕ',()=>{this.ride={npc,id,ticks:0,until:World.frame+1800};npc.wait=0;UI.toast('Держись за машиной 10 секунд, дистанция до 350');}]);UI.dialog(this.portrait(id),info.name+': узнаю тебя. '+(job?.state==='active'?'Жду чистый результат 60+ баллов.':'Что сегодня делаем?'),buttons);},
 updateRide(){const ride=this.ride;if(!ride)return;if(World.frame>ride.until||!World.npcs.includes(ride.npc)){this.ride=null;UI.toast('Совместный заезд закончен. Попробуй держаться ближе.');return;}const d=Math.hypot(car.x-ride.npc.x,car.y-ride.npc.y);if(d>carH()&&d<350&&Math.hypot(car.vx,car.vy)>3)ride.ticks++;if(ride.ticks>=600){this.ride=null;Save.state.social.lastRide[ride.id]=Date.now();Save.state.money+=400;Save.state.social.relations[ride.id]=(Save.state.social.relations[ride.id]||0)+1;this.draft('story',45,{person:ride.id,caption:'Совместный заезд: '+this.people[ride.id].name});Save.persist();UI.toast('Совместный заезд · +400 ₽ · story в черновиках');}},
 offerPhoto(event){UI.dialog(event.person?this.portrait(event.person):6,event.caption+'. Кадр учитывает текущую машину и тюнинг.',[['ОПУБЛИКОВАТЬ',()=>this.publish(event.id)],['СОХРАНИТЬ ЧЕРНОВИК',()=>{}]]);},
 async paint(canvas,event){const g=canvas.getContext('2d');g.imageSmoothingEnabled=false;const background=this.image('assets/runtime/'+(event.track||'wheel')+'.webp'),hero=this.image('assets/social/homeboy-'+(event.outfit||0)+'.webp'),def=CATALOG.cars.find(c=>c.id===event.car)||Vehicles.current(),vehicle=Vehicles.image(def,'preview',event.custom||{});await Promise.allSettled([background.decode(),hero.decode(),vehicle.decode()]);if(!canvas.isConnected)return;g.fillStyle='#111c29';g.fillRect(0,0,canvas.width,canvas.height);if(background.naturalWidth){g.globalAlpha=.45;g.drawImage(background,0,0,canvas.width,canvas.height);g.globalAlpha=1;}
  const contain=(im,x,y,w,h)=>{if(!im.naturalWidth)return;const z=Math.min(w/im.naturalWidth,h/im.naturalHeight);g.drawImage(im,x+(w-im.naturalWidth*z)/2,y+(h-im.naturalHeight*z)/2,im.naturalWidth*z,im.naturalHeight*z);};
  if(event.kind==='video'){const onboard=this.image('assets/social/onboard.webp');await onboard.decode().catch(()=>{});if(!canvas.isConnected)return;contain(onboard,0,0,canvas.width*.5,canvas.height);}
  contain(vehicle,canvas.width*.25,canvas.height*.40,canvas.width*.72,canvas.height*.55);if(!event.author)contain(hero,canvas.width*.04,canvas.height*.13,canvas.width*.30,canvas.height*.72);
  const person=this.people[event.person];if(person){const partner=Vehicles.image(CATALOG.cars.find(c=>c.id===person.car),'preview');const portrait=this.image('assets/characters.png');await Promise.allSettled([partner.decode(),portrait.decode()]);if(!canvas.isConnected)return;contain(partner,canvas.width*.43,canvas.height*.04,canvas.width*.52,canvas.height*.35);if(['artak','osman','gocha','tsar'].includes(event.person)){const face=this.image('assets/social/'+event.person+'.webp');await face.decode().catch(()=>{});if(!canvas.isConnected)return;contain(face,canvas.width*.65,canvas.height*.30,canvas.width*.18,canvas.width*.18);}else if(portrait.naturalWidth){const sw=portrait.width/3,sh=portrait.height/3;g.drawImage(portrait,person.portrait%3*sw,Math.floor(person.portrait/3)*sh,sw,sh,canvas.width*.65,canvas.height*.30,canvas.width*.18,canvas.width*.18);}}
  g.fillStyle='#f4c34d';g.font='bold 17px monospace';g.fillText(event.kind==='video'?'DRIFT VIDEO':event.person?person.name:'HOMEBOY',12,25);
 },
 open(view='profile',index=0){this.decay();const s=Save.state.social,root=UI.panel('ДОЛБОГРАММ'),layout=UI.el('div',{className:'social-layout'}),phone=UI.el('div',{className:'social-phone '+(view==='profile'?'social-profile':'social-feed')}),side=UI.el('div',{className:'social-details'});root.append(layout);layout.append(phone,side);phone.append(UI.el('img',{src:'assets/social/phone-'+(view==='profile'?'profile':'feed')+'.webp',alt:'Телефон Долбограмма',className:'phone-frame'}));
  const tabs=UI.el('div',{className:'toolbar'});for(const [id,label] of [['profile','ПРОФИЛЬ'],['posts','ПОСТЫ'],['drafts','ЧЕРНОВИКИ'],['stories','STORIES'],['feed','ЛЕНТА']])tabs.append(UI.el('button',{onclick:()=>this.open(id)},label));side.append(tabs,UI.el('h2',{},'Хоумбой'),UI.el('p',{},s.followers+' подписчиков · '+s.following.length+' подписки'),UI.el('p',{},s.views+' просмотров · '+s.likes+' лайков'),UI.el('p',{},'Внимание полиции: '+Math.round(s.attention)+'%'),UI.el('progress',{max:100,value:s.attention}));
  side.append(UI.el('h3',{},'ПАРНЫЕ ЗАЕЗДЫ'));for(const id of ['borsh','hustler'])side.append(UI.el('button',{disabled:s.followers<5000,onclick:()=>Tandem.challenge(id)},'ВЫЗВАТЬ '+(id==='borsh'?'БОРЩА':'ХАСЛЕРА')));if(s.followers<5000)side.append(UI.el('p',{},'Доступно с 5 000 подписчиков'));
  if(view==='profile'){const stats=UI.el('div',{className:'phone-stats'},s.posts.length+' постов · '+s.followers+' подписчиков');phone.append(stats);const grid=UI.el('div',{className:'phone-grid'});phone.append(grid);for(const event of s.posts.slice(0,6)){const c=UI.el('canvas',{width:240,height:240});grid.append(c);this.paint(c,event);c.onclick=()=>this.open('posts',s.posts.indexOf(event));}side.append(UI.el('img',{src:'assets/social/homeboy-'+s.outfit+'.webp',alt:'Твой персонаж Хоумбой',className:'homeboy-preview'}),UI.el('h3',{},'ОДЕЖДА'));
   this.outfits.forEach((o,i)=>side.append(UI.el('button',{disabled:s.outfit===i||(!s.outfits.includes(i)&&Save.state.money<o.price),onclick:()=>{if(!s.outfits.includes(i)){if(Save.state.money<o.price)return;Save.state.money-=o.price;s.outfits.push(i);}s.outfit=i;Save.persist();UI.balance();this.open();}},o.name+(s.outfits.includes(i)?' · НАДЕТЬ':' · '+o.price+' ₽'))));
  }else{const events=view==='feed'?Object.entries(this.people).map(([id,p])=>({id:'crew-'+id,kind:'photo',quality:30,car:p.car,custom:{},outfit:0,track:['hustler','grey'].includes(id)?'shop':'isakiy',person:id,author:id,caption:p.name+' · сегодня на тренировке',views:1200,likes:145,date:Date.now()})):view==='drafts'?s.drafts:view==='stories'?s.posts.filter(p=>p.person||p.kind==='story'):s.posts,event=events[index%Math.max(1,events.length)];if(event){const c=UI.el('canvas',{className:'phone-post',width:600,height:600});phone.append(c);this.paint(c,event);side.append(UI.el('h3',{},event.caption||'Story'),UI.el('p',{},new Date(event.date).toLocaleString('ru')),UI.el('p',{},(event.views||0)+' просмотров · '+(event.likes||0)+' лайков'));if(event.person&&this.people[event.person]?.art)side.append(UI.el('img',{src:'assets/social/'+this.people[event.person].art+'.webp',className:'story-reference',alt:'Story '+this.people[event.person].name}));if(view==='feed'){side.append(UI.el('button',{onclick:()=>{const id=event.author;s.following=s.following.includes(id)?s.following.filter(x=>x!==id):[...s.following,id];Save.persist();this.open(view,index);}},s.following.includes(event.author)?'ОТПИСАТЬСЯ':'ПОДПИСАТЬСЯ'),UI.el('button',{onclick:()=>{s.liked=s.liked.includes(event.id)?s.liked.filter(x=>x!==event.id):[...s.liked,event.id];Save.persist();this.open(view,index);}},s.liked.includes(event.id)?'♥ НРАВИТСЯ':'♡ НРАВИТСЯ'));}if(view==='drafts')side.append(UI.el('button',{onclick:()=>{this.publish(event.id);this.open('drafts');}},'ВЫЛОЖИТЬ'));if(events.length>1)side.append(UI.el('button',{onclick:()=>this.open(view,index+1)},'СЛЕДУЮЩИЙ'));}else side.append(UI.el('p',{},view==='drafts'?'Черновиков пока нет. Заверши заезд или сфотографируй машину.':'Пока нет публикаций.'));}
  side.append(UI.el('p',{className:'muted'},'Это внутриигровая локальная сеть. Публикации не отправляются в интернет.'));
 },
 service(){const s=Save.state.social,free=s.followers>=500&&Date.now()-(s.lastService||0)>86400000;UI.dialog(3,free?'Кирилл: переобуем бесплатно за story с отметкой WheelDoctors.':'Кирилл: комплект резины — 750 ₽. От 500 подписчиков возможна услуга за story раз в сутки.',[[free?'STORY ЗА ШИНОМОНТАЖ':'ЗАМЕНИТЬ · 750 ₽',()=>{if(!free&&Save.state.money<750){UI.toast('Недостаточно денег');return;}if(!free)Save.state.money-=750;Save.state.tires=100;if(free){const event=this.draft('story',30,{illegal:false,caption:'@wheeldoctors — свежая резина'});s.lastPost=0;this.publish(event.id);s.lastService=Date.now();}Save.persist();UI.toast('Шины: 100%');}]]);}
};
Social.init();
for(const [id,name,goal] of [['social100','Первые 100',100],['social1000','Медийный',1000],['social10000','Звезда',10000]])Achievements.push({id,name,goal,value:s=>s.social?.followers||0,reward:goal/2});
for(const [id,name] of [['borsh','Первая встреча'],['gocha','Редкий кадр'],['tsar','Царский кадр']])Achievements.push({id:'photo-'+id,name,goal:1,value:s=>s.social?.relations?.[id]||0,reward:500});
Achievements.push({id:'social-friends',name:'Свой в тусовке',goal:4,value:s=>Object.keys(s.social?.relations||{}).length,reward:1000});
