/* Repository boundary: replace this adapter to support a server leaderboard. */
const Save = (()=>{
 const qa=new URLSearchParams(location.search).has('qa');const key='raremasters.replay.progress.v1'+(qa?'.qa':'');const legacyKey='raremasters.progress.v1'+(qa?'.qa':'');
 const fresh=()=>({version:1,money:2500,total:0,distance:0,donuts:0,runs:0,clean:0,perfect:0,respect:0,tires:100,owned:['baseline'],selected:'baseline',custom:{},achievements:[],trackPoints:{},tutorial:true,settings:{music:true,sound:true,engine:true,drift:true,effects:true,ghost:true,quality:'auto',volume:.3,track:0,zoom:1}});
 let state=fresh();
 try {const raw=JSON.parse(localStorage.getItem(key)||localStorage.getItem(legacyKey)||'null');if(raw&&raw.version===1)state={...state,...raw,settings:{...state.settings,...raw.settings}};}catch(e){console.warn('Сохранение не прочитано',e);}
 let dbPromise;
 function db(){return dbPromise??=new Promise((resolve,reject)=>{const r=indexedDB.open('raremasters-replay-runs'+(qa?'-qa':''),3);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains('npcReplays')){const n=d.createObjectStore('npcReplays',{keyPath:'id'});n.createIndex('bucket','bucket');}if(!d.objectStoreNames.contains('runs'))d.createObjectStore('runs',{keyPath:'id'});if(!d.objectStoreNames.contains('summaries')){const summary=d.createObjectStore('summaries',{keyPath:'id'});const cursor=r.transaction.objectStore('runs').openCursor();cursor.onsuccess=()=>{const c=cursor.result;if(c){const {frames,...meta}=c.value;summary.put(meta);c.continue();}}}};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
 async function operation(mode,fn){const d=await db();return new Promise((resolve,reject)=>{const tx=d.transaction('runs',mode);const req=fn(tx.objectStore('runs'));tx.oncomplete=()=>resolve(req.result);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);});}
 let legacyPromise;
 async function legacy(store,id){try{const d=await(legacyPromise??=new Promise(resolve=>{const q=indexedDB.open('raremasters-runs'+(qa?'-qa':''));q.onupgradeneeded=()=>q.transaction.abort();q.onsuccess=()=>resolve(q.result);q.onerror=()=>resolve(null);}));if(!d||!d.objectStoreNames.contains(store))return id?null:[];return await new Promise((resolve,reject)=>{const s=d.transaction(store,'readonly').objectStore(store),q=id?s.get(id):s.getAll();q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error);});}catch(e){return id?null:[];}}
 function persist(){try{localStorage.setItem(key,JSON.stringify(state));return true;}catch(e){if(window.UI)UI.toast('Не удалось сохранить прогресс: хранилище заполнено');return false;}}
 return {get state(){return state;},persist,async list(track,direction,mode){const d=await db();const all=await new Promise((resolve,reject)=>{const q=d.transaction('summaries').objectStore('summaries').getAll();q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error);});const merged=new Map((await legacy('summaries')).map(r=>[r.id,r]));for(const r of all)merged.set(r.id,r);return [...merged.values()].filter(r=>(!track||r.track===track)&&(!direction||r.direction===direction)&&(!mode||r.mode===mode)).sort((a,b)=>b.score-a.score||a.elapsed-b.elapsed);},async put(run){if(run.mode!=='competition')return;const d=await db();await new Promise((resolve,reject)=>{const tx=d.transaction(['runs','summaries'],'readwrite');tx.objectStore('runs').put(run);const {frames,...summary}=run;tx.objectStore('summaries').put(summary);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});},async get(id){return await operation('readonly',s=>s.get(id))||await legacy('runs',id);},async npcList(bucket){const d=await db();return new Promise((resolve,reject)=>{const q=d.transaction('npcReplays').objectStore('npcReplays').index('bucket').getAll(bucket);q.onsuccess=()=>resolve(q.result.sort((a,b)=>a.date-b.date));q.onerror=()=>reject(q.error);});},async npcPut(record){const d=await db();return new Promise((resolve,reject)=>{const tx=d.transaction('npcReplays','readwrite'),store=tx.objectStore('npcReplays');store.put(record);const q=store.index('bucket').getAll(record.bucket);q.onsuccess=()=>{const rows=q.result.sort((a,b)=>b.date-a.date);for(const row of rows.slice(6))store.delete(row.id);};tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});},async npcClear(bucket){const d=await db();return new Promise((resolve,reject)=>{const tx=d.transaction('npcReplays','readwrite'),store=tx.objectStore('npcReplays'),q=store.index('bucket').getAllKeys(bucket);q.onsuccess=()=>q.result.forEach(id=>store.delete(id));tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});},async export(){const d=await db(),npcReplays=await new Promise((resolve,reject)=>{const q=d.transaction('npcReplays').objectStore('npcReplays').getAll();q.onsuccess=()=>resolve(q.result.map(r=>({...r,frames:Array.from(r.frames)})));q.onerror=()=>reject(q.error);});return {progress:state,runs:await operation('readonly',s=>s.getAll()),npcReplays};}};
})();
const Achievements=[
 {id:'artak',name:'Семёрка Артака',goal:120000,value:s=>s.total,reward:1500,car:'artak'},
 {id:'borsh',name:'Слива Борща',goal:400000,value:s=>s.total,reward:2000,car:'borsh'},
 {id:'subaru',name:'Subaru Борща',goal:650000,value:s=>s.total,reward:3000,car:'subaru'},
 {id:'first',name:'Первый финиш',goal:1,value:s=>s.runs,reward:1000},
 {id:'clean',name:'Чистая линия',goal:1,value:s=>s.clean,reward:1500},
 {id:'sixty',name:'Олдскульный стиль',goal:300000,value:s=>s.total,reward:2500,car:'oldschool'},
 {id:'hundred',name:'Большая лига',goal:1500000,value:s=>s.total,reward:4000,car:'gocha'},
 {id:'tsar',name:'Царь дрифта',goal:2500000,value:s=>s.total,reward:6000,car:'tsar'},
 {id:'hustler',name:'Свой у Михалыча',goal:250000,value:s=>s.trackPoints.shop||0,reward:2500,car:'hustler'},
 {id:'clips',name:'Десять идеальных clipping',goal:10,value:s=>s.perfect,reward:3000},
 {id:'donuts',name:'Бублик',goal:10,value:s=>s.donuts,reward:1000},
 {id:'travel',name:'Путешественник',goal:100000,value:s=>s.distance,reward:2000}
];
const Economy={
 audio(){const s=Save.state;if(!s.audioSystem)s.audioSystem={level:'none',installed:false,tracks:[]};return s.audioSystem;},
 audioTracks(){const a=this.audio();return !a.installed||a.level==='none'?[]:a.level==='pro'?CATALOG.music.map((_,i)=>i):a.tracks;},
 buyAudio(level){const a=this.audio(),s=Save.state;if(!['standard','pro'].includes(level)||a.level==='pro'||a.level===level)return false;const price=level==='standard'?10000:a.level==='standard'?40000:50000;if(s.money<price)return false;const previous=JSON.parse(JSON.stringify(a));s.money-=price;a.level=level;if(level==='standard'){a.tracks=CATALOG.music.map((_,i)=>i);for(let i=a.tracks.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a.tracks[i],a.tracks[j]]=[a.tracks[j],a.tracks[i]];}a.tracks=a.tracks.slice(0,20);}if(!Save.persist()){s.money+=price;s.audioSystem=previous;return false;}return true;},
 installAudio(){const a=this.audio(),s=Save.state;if(a.level==='none'||a.installed||s.money<10000)return false;s.money-=10000;a.installed=true;if(!Save.persist()){s.money+=10000;a.installed=false;return false;}return true;},
 check(){const s=Save.state;for(const a of Achievements)if(!s.achievements.includes(a.id)&&a.value(s)>=a.goal){s.achievements.push(a.id);s.money+=a.reward;if(a.car)UI.toast('Открыта покупка: '+a.name);window.UI?.toast(`Достижение: ${a.name} · +${a.reward} ₽`);}Save.persist();},
 earn(points){if(!Number.isFinite(points)||points<=0)return;const s=Save.state;s.total+=points;s.trackPoints[selectedMapId]=(s.trackPoints[selectedMapId]||0)+points;s.money+=points/20;s.respect+=points/100;},
 unlocked(c){return c.bonus?Achievements.some(a=>a.car===c.id&&Save.state.achievements.includes(a.id)):Save.state.total>=c.unlock;},
 buy(id){const c=CATALOG.cars.find(c=>c.id===id),s=Save.state;if(!c||s.owned.includes(id)||!this.unlocked(c)||s.money<c.price)return false;s.money-=c.price;s.owned.push(id);Save.persist();return true;},
 custom(kind,value){const s=Save.state;const prices={paint:300,rims:500,aero:1000};const expanded=['baseline','rare','silvia'].includes(s.selected),limit=expanded&&kind!=='aero'?3:1;if(!(kind in prices)||!Number.isInteger(value)||value<0||value>limit)return false;const old=s.custom[s.selected]||{};if(kind==='rims'&&value>1&&(old.paint||0)<2||kind==='paint'&&value<2&&(old.rims||0)>1)return false;const conf=s.custom[s.selected]??={color:0,wheels:0,bodykit:0,paid:[]};const k=kind+value;if(!conf.paid.includes(k)&&value!==0){if(s.money<prices[kind])return false;s.money-=prices[kind];conf.paid.push(k);}conf[kind]=value;Save.persist();return true;}
};

// Refund retired broken rectangle cosmetics once; preserve cars and progression.
if(!Save.state.cosmeticMigration){for(const conf of Object.values(Save.state.custom)){for(const key of conf.paid||[]){if(key.startsWith('color'))Save.state.money+=300;else if(key.startsWith('wheels'))Save.state.money+=500;else if(key.startsWith('bodykit'))Save.state.money+=1000;}conf.legacy={color:conf.color,wheels:conf.wheels,bodykit:conf.bodykit};conf.color=conf.wheels=conf.bodykit=0;}Save.state.cosmeticMigration=1;Save.persist();}

if(!Save.state.independentCosmetics){for(const conf of Object.values(Save.state.custom)){conf.paid??=[];if(conf.build===1){conf.paint=1;conf.paid.push('paint1');Save.state.money+=500;}if(conf.build===2){conf.rims=conf.aero=1;conf.paid.push('rims1','aero1');}delete conf.build;}Save.state.independentCosmetics=1;Save.persist();}

if(!Save.state.audioChannels){for(const k of ['engine','drift','effects'])Save.state.settings[k]=Save.state.settings.sound!==false;Save.state.audioChannels=1;Save.persist();}

// Keep cars already owned; unmet legacy unlocks no longer grant a new purchase.
if(!Save.state.bonusEconomyV2){Save.state.achievements=Save.state.achievements.filter(id=>{const a=Achievements.find(a=>a.id===id);return !a?.car||Save.state.owned.includes(a.car)||a.value(Save.state)>=a.goal;});Save.state.bonusEconomyV2=1;Save.persist();}
