/* Two legs, shared road controller, measured judging; no replay masquerading as AI. */
const Tandem={active:false,battle:null,
 reset(){this.active=false;this.battle=null;this.npc=null;this.trail=[];},
 invite(){return false;},
 offer(score){if(score<80||comp?.invalid||Math.random()>=.08)return;const id=Math.random()<.5?'gocha':'tsar';UI.dialog(Social.portrait(id),Social.people[id].name+': хороший заезд. Поедем парный? Два прохода: сначала я впереди, затем ты.',[['ПРИНЯТЬ',()=>this.start(id,selectedMapId)],['ОТКАЗАТЬСЯ',()=>{}]]);},
 challenge(id){if(!['borsh','hustler'].includes(id)||Save.state.social.followers<5000){UI.toast('Доступно с 5 000 подписчиков');return;}UI.tracks('legal',id);},
 async start(id,track){if(!['gocha','tsar','borsh','hustler'].includes(id))return false;if(['borsh','hustler'].includes(id)&&Save.state.social.followers<5000)return false;await Game.start(track,'competition');if(selectedMapId!==track||!gameRunning)return false;document.getElementById('rmDialog').style.display='none';this.battle={id,track,leg:1,results:[]};this.setup();return true;},
 setup(){const b=this.battle;baseline.resetCar();car.angle=Tracks.usesRoute()?Tracks.spawnAngle:0;Replay.ghost=null;Replay.reset();Traffic.build();World.npcs=[];World.cops=[];if(!Traffic.length){this.reset();UI.toast('Не удалось построить безопасную траекторию');return;}let at=0,best=Infinity;for(let d=0;d<Traffic.length;d+=20){const p=Traffic.point(d),dist=Math.hypot(p.x-car.x,p.y-car.y);if(dist<best){best=dist;at=d;}}const start=Traffic.point(at+80);car.angle=Math.atan2(start.y-car.y,start.x-car.x);const gap=carH()*2.2,n=Traffic.create(Social.people[b.id].car,at+(b.leg===1?gap:-gap),Social.people[b.id].portrait);if(!n){this.reset();return;}Object.assign(n,{kind:'tandem',special:true,person:b.id,profile:['gocha','tsar'].includes(b.id)?'pro':'advanced',travelled:0,contacts:0});if(b.leg===2){for(const d of [gap,gap*.8,gap*.65]){const x=car.x-Math.cos(car.angle)*d,y=car.y-Math.sin(car.angle)*d;if(World.safe(x,y,car.angle)){n.x=x;n.y=y;n.angle=car.angle;break;}}}this.npc=n;World.npcs=[n];this.trail=[];this.judge=RaceJudge.create();this.follow={quality:0,samples:0,contacts:0};this.ticks=0;this.contactAt=-60;this.npcFinished=false;this.active=true;gamePaused=true;keys={};AudioPlayer.stopGame();showScreen('game');UI.dialog(Social.portrait(b.id),'ПРОХОД '+b.leg+'/2 · '+(b.leg===1?'Соперник лидирует. Следуй за ним и держи дистанцию.':'Ты лидируешь. Соперник следует твоей траектории.'),[['СТАРТ',()=>{gamePaused=false;keys={};}]]);},
 update(){if(!this.active||gamePaused||!this.npc)return;this.ticks++;const n=this.npc,b=this.battle,old={x:n.x,y:n.y};
  if(b.leg===1){const distance=Math.hypot(car.x-n.x,car.y-n.y),cap=Math.max(3,Math.min(8,Vehicles.current().stats.topSpeed*9.4));if(this.npcFinished&&n.finishExit){Traffic.drive(n,{target:n.finishExit,speed:Math.hypot(n.x-n.finishExit.x,n.y-n.finishExit.y)>15?3:0,slip:0});}else Traffic.drive(n,{cap:distance>300?Math.min(cap,Math.max(2,Math.hypot(car.vx,car.vy)+(330-distance)*.006)):cap});}
  else{const last=this.trail.at(-1);if(!last||Math.hypot(last.x-car.x,last.y-car.y)>12)this.trail.push({x:car.x,y:car.y,angle:car.angle});if(this.trail.length>400)this.trail.shift();let distance=0,target=null;for(let i=this.trail.length-1;i>0;i--){distance+=Math.hypot(this.trail[i].x-this.trail[i-1].x,this.trail[i].y-this.trail[i-1].y);if(distance>=carH()*1.8){target=this.trail[i-1];break;}}const hasTrail=!!target;target??={x:n.x,y:n.y,angle:n.angle};const gap=Math.hypot(car.x-n.x,car.y-n.y),playerSpeed=Math.hypot(car.vx,car.vy),wanted=Math.max(0,Math.min(Vehicles.current().stats.topSpeed*10,playerSpeed+(gap-carH()*2)*.016));const targetHeading=Math.atan2(target.y-n.y,target.x-n.x),slip=wrap((target.angle??targetHeading)-targetHeading);Traffic.drive(n,{target,speed:!hasTrail||gap<carH()*1.5?0:wanted,slip:Math.max(-.5,Math.min(.5,slip))});}
  if(World.contact(car,n)){World.resolve(car,n);if(this.ticks-this.contactAt>30){this.follow.contacts++;n.contacts++;Replay.hits++;this.contactAt=this.ticks;}}
  if(comp?.startCrossed){if(!this.npcFinished)RaceJudge.sample(this.judge,n);const leader=b.leg===1?n:car,follower=b.leg===1?car:n,dist=Math.hypot(leader.x-follower.x,leader.y-follower.y),alignment=Math.abs(wrap(leader.angle-follower.angle)),behind=(leader.x-follower.x)*Math.cos(leader.angle)+(leader.y-follower.y)*Math.sin(leader.angle)>0;this.follow.samples++;this.follow.quality+=behind?Math.max(0,1-Math.abs(dist-carH()*1.9)/(carH()*3))*Math.max(0,1-alignment/1.2):0;}
  if(!this.npcFinished&&n.travelled>500&&lineTouched(markers.lines[1],old.x,old.y,n.x,n.y)){this.npcFinished=true;const h=Math.atan2(n.vy,n.vx);for(const sign of [-1,1]){const p={x:n.x+Math.cos(h)*carH()*2-Math.sin(h)*carW()*2.5*sign,y:n.y+Math.sin(h)*carH()*2+Math.cos(h)*carW()*2.5*sign};if(Traffic.clear(n,p)){n.finishExit=p;break;}}}
  if(this.ticks>10800)invalidateCompetition('ВРЕМЯ ПАРНОГО ЗАЕЗДА ИСТЕКЛО');
 },
 result(){if(!this.active)return false;const b=this.battle,n=this.npc,follow=Math.max(0,Math.min(100,this.follow.quality/Math.max(1,this.follow.samples)*100-this.follow.contacts*3)),npcLine=RaceJudge.score(this.judge,0,maxSpeed()).score,playerLine=comp.invalid?0:comp.score;const leg=b.leg===1?{player:comp.invalid?0:follow,opponent:Math.max(0,npcLine-n.contacts*3),contacts:this.follow.contacts}:{player:Math.max(0,playerLine-Replay.hits*3),opponent:follow,contacts:this.follow.contacts};b.results.push(leg);gamePaused=true;AudioPlayer.stopGame();this.active=false;
  if(b.leg===1){UI.dialog(Social.portrait(b.id),'ПРОХОД 1/2 · Ты (преследование): '+leg.player.toFixed(1)+' · '+Social.people[b.id].name+' (лидирование): '+leg.opponent.toFixed(1),[['ВТОРОЙ ПРОХОД',()=>{b.leg=2;this.battle=b;this.setup();}],['ЗАВЕРШИТЬ БЕЗ РЕЗУЛЬТАТА',()=>{this.reset();leaveGame();}]]);return true;}
  const total=b.results.reduce((a,r)=>({player:a.player+r.player,opponent:a.opponent+r.opponent}),{player:0,opponent:0}),p=Math.round(total.player*100)/100,o=Math.round(total.opponent*100)/100,winner=p===o?'НИЧЬЯ':p>o?'ИГРОК':Social.people[b.id].name.toUpperCase();Save.state.tandemResults??=[];Save.state.tandemResults.unshift({opponent:b.id,track:b.track,results:b.results,player:p,opponentScore:o,winner,date:Date.now()});Save.state.tandemResults=Save.state.tandemResults.slice(0,20);Save.persist();const root=UI.panel('ПАРНЫЙ ЗАЕЗД ЗАВЕРШЁН');root.append(UI.el('h2',{},winner==='НИЧЬЯ'?'НИЧЬЯ':'ПОБЕДИЛ: '+winner));for(let i=0;i<2;i++)root.append(UI.el('p',{},'Проход '+(i+1)+' · ИГРОК '+b.results[i].player.toFixed(1)+' : '+Social.people[b.id].name+' '+b.results[i].opponent.toFixed(1)));root.append(UI.el('h3',{},'ИТОГО · ИГРОК '+p+' : '+Social.people[b.id].name+' '+o),UI.el('p',{},'Лидирование: LINE 40 + ANGLE 40 + STYLE 20. Преследование: дистанция, направление и синхронность. Контакты уменьшают оценку.'),UI.el('button',{onclick:()=>{this.reset();leaveGame();}},'В МЕНЮ'));this.battle=null;return true;
 }
};
