/* Traffic follows one connected road circuit. Body slip is separate from velocity. */
const Traffic={route:[],cache:new Map(),
 // The supplied Autodrom has pixel markers rather than a route. Keep its scoring mask unchanged.
 legalAnchors:[[.408,.507],[.455,.495],[.53,.48],[.574,.451],[.588,.407],[.588,.3],[.592,.229],[.61,.173],[.641,.154],[.653,.177],[.662,.252],[.68,.279],[.711,.288],[.745,.278],[.771,.279],[.781,.301],[.766,.334],[.72,.397],[.66,.477],[.6,.549],[.53,.583],[.445,.602],[.385,.614],[.357,.644],[.369,.699],[.395,.769],[.391,.827],[.367,.866],[.326,.88],[.288,.859],[.265,.81],[.256,.744],[.26,.665],[.281,.603],[.318,.555],[.359,.524]],
 trainingReset(){this.nextDriverAt=600;this.trainingLimit=Save.state.settings.quality==='low'?2:3;this.build();this.pitDistance=0;if(!this.length)return;for(let i=0;i<this.trainingLimit;i++)this.spawnDriver(this.length*(i+1)/(this.trainingLimit+1));},
 spawnDriver(distance){if(!this.length)return false;const p=this.point(distance);if(!p||Math.hypot(p.x-car.x,p.y-car.y)<carH()*5||World.npcs.some(n=>Math.hypot(p.x-n.x,p.y-n.y)<carH()*3))return false;const roll=Math.random(),id=roll<.005?'gocha':roll<.01?'tsar':['borsh','hustler','rare','grey','artak'][Math.floor(Math.random()*5)],person=Social.people[id],n=this.create(person.car,distance,person.portrait);if(!n||!World.safe(n.x,n.y,n.angle))return false;Object.assign(n,{kind:'drifter',special:true,person:id,profile:['gocha','tsar'].includes(id)?'pro':'advanced',laps:0,leaveAfter:2+Math.floor(Math.random()*4),originDistance:distance,travelled:0});World.npcs.push(n);return true;},
 trainingUpdate(){for(const n of [...World.npcs]){if(n.kind==='drifter'){this.drive(n);n.laps=Math.floor(n.travelled/this.length);if(n.laps>=n.leaveAfter)n.pitting=true;if(n.pitting&&(n.distance%this.length)<150){if(!n.pit){const base=this.point(0);for(const sign of [-1,1]){const p={x:base.x-Math.sin(n.angle)*carW()*2*sign,y:base.y+Math.cos(n.angle)*carW()*2*sign};if(this.clear(base,p)){n.pit=p;break;}}n.pit??=base;n.kind='pit';n.pitTicks=0;}}}else if(n.kind==='pit'){n.pitTicks++;this.drive(n,{target:n.pit,speed:Math.hypot(n.x-n.pit.x,n.y-n.pit.y)>15?2:0});if(n.pitTicks>180&&Math.hypot(n.x-car.x,n.y-car.y)>carH()*4){World.npcs.splice(World.npcs.indexOf(n),1);this.nextDriverAt=World.frame+600+Math.floor(Math.random()*1200);}}if(World.contact(n,car)){World.resolve(car,n);n.contacts=(n.contacts||0)+1;Replay.hits++;}for(const b of World.npcs)if(b!==n&&World.contact(n,b))World.resolve(n,b);}if(World.npcs.length<this.trainingLimit&&World.frame>=this.nextDriverAt){this.spawnDriver(this.pitDistance);this.nextDriverAt=World.frame+300;}},
 project(v){const scratch=this.projectPoint??=( {x:0,y:0});let best=null;const local=v.distance||0;for(let d=local-80;d<=local+250;d+=15){const p=this.point(d,scratch),error=Math.hypot(p.x-v.x,p.y-v.y);if(!best||error<best.error){best=this.projectResult??={distance:0,error:0};best.distance=d;best.error=error;}}return best;},
 drive(n,options={}){if(!this.length)return;if(!options.target&&typeof NpcReplay!=='undefined'&&NpcReplay.drive(n))return;const old={x:n.x,y:n.y,angle:n.angle},speed=Math.hypot(n.vx,n.vy),projection=this.project(n);if(!options.target&&projection){const delta=Math.max(0,Math.min(Math.hypot(n.vx,n.vy)*1.4+.5,projection.distance-n.distance));n.distance+=delta;n.travelled=(n.travelled||0)+delta;}const look=30+speed*5,target=options.target||this.point(n.distance+look),far=this.point(n.distance+look+130),heading=Math.atan2(target.y-n.y,target.x-n.x),bend=wrap(Math.atan2(far.y-target.y,far.x-target.x)-heading),error=projection?.error||0;let wanted=options.speed??Math.max(1.5,Math.min(6,(n.profile==='pro'?6:5.7)/(1+Math.abs(bend)*2.5)));if(!options.target&&error>60)wanted=Math.min(wanted,3);if(!options.target&&Math.abs(wrap(heading-(speed>.5?Math.atan2(n.vy,n.vx):n.angle)))>.6)wanted=Math.min(wanted,3);
  if(n.kind==='drifter'&&selectedMapId==='igor'&&!options.target){const lane=carW()*.8,x=target.x-Math.sin(heading)*lane,y=target.y+Math.cos(heading)*lane;if(World.safe(x,y,heading)){target.x=x;target.y=y;}}
  wanted=Math.min(wanted,options.cap??Infinity);for(const other of [car,...World.npcs])if(other!==n){const dx=other.x-n.x,dy=other.y-n.y,f=dx*Math.cos(heading)+dy*Math.sin(heading),side=Math.abs(-dx*Math.sin(heading)+dy*Math.cos(heading));if(f>0&&f<carH()*3&&side<carW()*1.3)wanted=Math.min(wanted,Math.max(0,(f-carH()*1.4)*.035));}
  if(Math.abs(bend)>.12)n.driftSide=Math.sign(bend);const corner=speed>(selectedMapId==='igor'?2.5:3.5)&&Math.abs(bend)>.08?Math.sign(bend)*Math.min(selectedMapId==='isakiy'?.46:n.profile==='pro'?.78:.7,Math.abs(bend)*1.8):0;n.cornerSlip=(n.cornerSlip||0)+(corner-(n.cornerSlip||0))*(corner?.12:.025);const slip=options.slip??n.cornerSlip;Dynamics.drive(n,target,wanted,slip,n.profile==='pro'?1.08:1);const nx=n.x+n.vx,ny=n.y+n.vy;if(World.safe(nx,ny,n.angle)){n.x=nx;n.y=ny;n.blocked=0;}else{n.angle=Math.atan2(n.vy,n.vx);if(World.safe(nx,ny,n.angle)){n.x=nx;n.y=ny;n.blocked=0;}else{n.angle=old.angle;n.vx=n.vy=0;n.blocked=(n.blocked||0)+1;/* Reverse out under power; never jump to a waypoint. */const back={x:n.x-Math.cos(n.angle)*1.5,y:n.y-Math.sin(n.angle)*1.5};if(World.safe(back.x,back.y,n.angle)){n.x=back.x;n.y=back.y;}if(n.blocked>30)n.distance=Math.max(0,n.distance-30);}}
 },
 build(){Navigation.ready=false;Navigation.step=selectedMapId==='isakiy'?30:65;Navigation.build();const cacheKey=[selectedMapId,W,H,Tracks.direction].join(':');if(this.cache.has(cacheKey)){Object.assign(this,this.cache.get(cacheKey));return;}let anchors=(currentMap.route||(selectedMapId==='isakiy'?this.legalAnchors:[])).map(([x,y])=>({x:x*W,y:y*H}));if(gameType==='legal'&&Tracks.direction==='reverse')anchors.reverse();if(anchors.length)anchors=anchors.filter((p,i)=>i===0||Navigation.path(anchors[0],p).length);this.route=[];
  for(let i=0;i<anchors.length;i++){const a=anchors[i],b=anchors[(i+1)%anchors.length],path=Navigation.path(a,b);if(!path.length)continue;this.route.push(...path);}
  // Remove repeated points and shortcut only fully clear, swept road segments.
  const raw=this.route;this.route=[];for(let i=0;i<raw.length;){this.route.push(raw[i]);let next=i+1;for(let j=Math.min(raw.length-1,i+8);j>i+1;j--)if(this.clear(raw[i],raw[j])){next=j;break;}i=next;}
  this.lengths=[0];for(let i=0;i<this.route.length;i++){const a=this.route[i],b=this.route[(i+1)%this.route.length];this.lengths.push(this.lengths[i]+Math.hypot(a.x-b.x,a.y-b.y));}this.length=this.lengths.at(-1)||0;this.cache.set(cacheKey,{route:this.route,lengths:this.lengths,length:this.length});if(this.cache.size>6)this.cache.delete(this.cache.keys().next().value);
 },
 clear(a,b){const distance=Math.hypot(b.x-a.x,b.y-a.y),angle=Math.atan2(b.y-a.y,b.x-a.x);for(let d=0;d<=distance;d+=25){const t=distance?d/distance:0;if(![angle-.25,angle,angle+.25].every(q=>World.safe(a.x+(b.x-a.x)*t,a.y+(b.y-a.y)*t,q)))return false;}return World.safe(b.x,b.y,angle);},
 point(distance,out){if(!this.length)return null;distance=((distance%this.length)+this.length)%this.length;let lo=0,hi=this.route.length-1;while(lo<hi){const mid=(lo+hi)>>>1;if(this.lengths[mid+1]<distance)lo=mid+1;else hi=mid;}const a=this.route[lo],b=this.route[(lo+1)%this.route.length],t=(distance-this.lengths[lo])/(this.lengths[lo+1]-this.lengths[lo]||1);const p=out||{};p.x=a.x+(b.x-a.x)*t;p.y=a.y+(b.y-a.y)*t;return p;},
 create(id,distance,character){const p=this.point(distance),ahead=this.point(distance+80);if(!p||!ahead)return null;const avatar=Math.floor(Math.random()*5);const n={...p,angle:Math.atan2(ahead.y-p.y,ahead.x-p.x),vx:0,vy:0,distance,kind:'traffic',car:CATALOG.cars.find(c=>c.id===id),character,displayName:['Дима','Лена','Михаил','Катя','Рома'][avatar],avatar,wait:0,temperament:Math.random(),drifter:Math.random()<.3,behaviorAt:600+Math.floor(Math.random()*1200),behavior:'cruise'};Vehicles.sprite(n.car);return n;},
 update(n,dt=1){if(n.wait>0){n.wait=Math.max(0,n.wait-dt);n.vx=n.vy=0;return;}if(typeof NpcReplay!=='undefined'&&NpcReplay.drive(n,dt))return;if(n.retaliateUntil>World.frame){World.move(n,Navigation.steer(n,car),7);if(World.contact(n,car)){World.resolve(car,n);n.retaliateUntil=0;n.wait=120;}return;}
  const city=selectedMode==='city';
  if(n.circle){const t=n.circle,phase=t.phase+.055*dt,x=t.x+Math.cos(phase)*t.r,y=t.y+Math.sin(phase)*t.r,a=phase+Math.PI/2+.45;if(World.heat||!World.safe(x,y,a)||World.npcs.some(v=>v!==n&&Math.hypot(v.x-x,v.y-y)<carH()*1.7)){n.circle=null;}else{n.vx=x-n.x;n.vy=y-n.y;n.x=x;n.y=y;n.angle=a;t.phase=phase;if(phase>=Math.PI*3)n.circle=null;return;}}
  if(n.parking){const expired=World.frame>=n.parkUntil||World.heat>0,target=expired?this.point(n.distance):n.parking;if(target&&Math.hypot(n.x-target.x,n.y-target.y)>8)World.move(n,target,Math.min(3,dt*2));else{n.vx=n.vy=0;if(expired)n.parking=null;}return;}

  if(World.heat){n.behavior=n.drifter&&!n.special?'calm':'escape';n.wait=0;}
  else if(World.frame>n.behaviorAt){n.behaviorAt=World.frame+600+Math.floor(Math.random()*1200);n.behavior=Math.random()<.2?'yield':n.drifter&&!city?'drift':'cruise';if(n.behavior==='drift'&&Math.random()<.25){const radius=145,center={x:n.x+radius,y:n.y};let clear=true;for(let i=0;i<48;i++){const a=i*Math.PI/24,x=center.x+Math.cos(a)*radius,y=center.y+Math.sin(a)*radius;if(!World.safe(x,y,a+Math.PI/2+.45)||World.npcs.some(v=>v!==n&&Math.hypot(v.x-x,v.y-y)<carH()*2)){clear=false;break;}}if(clear)n.circle={...center,r:radius,phase:Math.PI};}if(n.behavior==='yield'){for(const sign of [-1,1]){const target={x:n.x-Math.sin(n.angle)*carW()*2.2*sign,y:n.y+Math.cos(n.angle)*carW()*2.2*sign};if(this.clear(n,target)&&World.npcs.every(v=>v===n||Math.hypot(v.x-target.x,v.y-target.y)>carH()*1.6)){n.parking=target;n.parkUntil=World.frame+240+Math.floor(Math.random()*360);break;}}}}
  let speed=city?2.5:4.8+n.temperament*2;if(n.behavior==='escape')speed=8.5;if(n.behavior==='calm')speed=4;if(n.behavior==='yield')speed=2;
  // Physical spacing also covers crossing route segments, not only path distance.
  for(const other of World.npcs)if(other!==n){const dx=other.x-n.x,dy=other.y-n.y,forward=dx*Math.cos(n.angle)+dy*Math.sin(n.angle),side=Math.abs(-dx*Math.sin(n.angle)+dy*Math.cos(n.angle));if(forward>0&&forward<carH()*2.4&&side<carW()*1.1)speed=Math.min(speed,Math.max(0,(forward-carH()*1.25)*.04));}
for(const other of World.npcs)if(other!==n){const gap=(other.distance-n.distance+this.length)%this.length;if(gap<220)speed*=Math.max(0,(gap-125)/95);}
  speed*=dt;const ahead=this.point(n.distance+130),pos=this.point(n.distance+speed);if(!ahead||!pos)return;const travel=Math.atan2(ahead.y-n.y,ahead.x-n.x),turn=wrap(travel-(n.travel??travel));n.travel=travel;const targetAngle=travel+(city||n.behavior!=='drift'?0:Math.max(-.52,Math.min(.52,turn*10)));n.angle+=Math.max(-.07,Math.min(.07,wrap(targetAngle-n.angle)));
  const shift=Math.min(speed,Math.hypot(pos.x-n.x,pos.y-n.y)),heading=Math.atan2(pos.y-n.y,pos.x-n.x);const x=n.x+Math.cos(heading)*shift,y=n.y+Math.sin(heading)*shift;
  if(World.safe(x,y,n.angle)){n.vx=x-n.x;n.vy=y-n.y;n.x=x;n.y=y;n.distance+=speed;n.blocked=speed<.1?(n.blocked||0)+dt:0;}else{n.angle=travel;n.blocked=(n.blocked||0)+1;if(World.safe(x,y,travel)){n.x=x;n.y=y;n.distance+=speed;}else if(n.blocked>120&&Math.hypot(n.x-car.x,n.y-car.y)>1200){const p=this.point(n.distance+150);if(p&&World.safe(p.x,p.y,travel)){n.x=p.x;n.y=p.y;n.distance+=150;n.blocked=0;}}}
 }
};




