const UI={panelVersion:0,dialogToken:0,
 el(tag,props={},text){const e=document.createElement(tag);Object.assign(e,props);if(text!==undefined)e.textContent=text;return e;},
 toast(s){const e=document.getElementById('rmToast');e.textContent=s;e.style.display='block';clearTimeout(this.toastTimer);this.toastTimer=setTimeout(()=>e.style.display='none',4000);},
 init(){
  const main=document.getElementById('mainMenu');main.innerHTML='<div class="rm-menu"><div class="menu-grid" id="mainActions"></div><div class="menu-footer"><span class="balance" id="money"></span></div><div class="sponsors"><img src="assets/sponsors/3g.png" alt="Спонсор"><img src="assets/sponsors/landing_logo_x3.png" alt="Спонсор"></div></div>';
  const actions=[['ЛЕГАЛ',()=>this.tracks('legal')],['НЕЛЕГАЛ',()=>this.tracks('illegal')],['ГОРОД',()=>Game.start('wheel','city')],['ГАРАЖ',()=>this.garage(false)],['ДОЛБОГРАММ',()=>Social.open()],['ДОСТИЖЕНИЯ',()=>this.achievements()],['РЕЙТИНГ',()=>this.leaderboard()],['⚙',()=>this.settings()]];actions.forEach(([s,f],i)=>{const b=this.el('button',{onclick:f,className:i<2?'primary':''},s);b.dataset.action=s;if(s==='⚙'){b.className='menu-settings';b.ariaLabel='Настройки';}if(s==='ДОЛБОГРАММ'){b.className='menu-dolbogram';b.textContent='';b.ariaLabel='DOLBOGRAM';b.append(this.el('img',{src:'assets/social/dolbogram-logo.webp',alt:'DOLBOGRAM',className:'dolbogram-logo'}));}document.getElementById('mainActions').append(b);});
  document.body.insertAdjacentHTML('beforeend','<div id="rmPanel" class="screen"></div><div id="rmToast"></div><div id="rmDialog"></div><div id="rmStatus" hidden></div><canvas id="miniMap" width="240" height="160" hidden></canvas><button id="serviceBtn" hidden>ЗАМЕНИТЬ ШИНЫ</button>');
  document.getElementById('serviceBtn').onclick=()=>World.service();
  const bar=document.getElementById('topGameBtns');bar.innerHTML='';for(const [s,f] of [['МЕНЮ',()=>leaveGame()],['ПАУЗА',()=>this.pause()],['МУЗЫКА',()=>this.music()],['ФОТО',()=>Social.photo()],['МЕСТА',()=>Guide.cityPlaces()],['GHOST',()=>{Replay.enabled=!Replay.enabled;Save.state.settings.ghost=Replay.enabled;Save.persist();this.toast(Replay.enabled?'Призрак включён':'Призрак выключен');}],['⚙',()=>this.settings()],...[.5,1,2].map(z=>[z+'×',()=>{Save.state.settings.zoom=z;setMobileCameraMultiplier(z);Save.persist();}])]){const button=this.el('button',{onclick:f},s);if(s==='МЕСТА')this.placesButton=button;bar.append(button);}
  this.ghostButton=[...bar.children].find(b=>b.textContent==='GHOST');this.balance();
 },
 balance(){document.getElementById('mainMenu').style.backgroundImage="url('menu/outfit-"+(Save.state.social?.outfit||0)+".webp')";document.getElementById('money').textContent=`${Math.floor(Save.state.money).toLocaleString('ru')} ₽ · ${Math.floor(Save.state.total).toLocaleString('ru')} DRIFT`;},
 panel(title){this.panelVersion++;if(gameRunning&&!this.panelPausedAt)this.panelPausedAt=performance.now();gamePaused=gameRunning;AudioPlayer.stopGame();window.clearDrivingControls?.();keys={};const e=document.getElementById('rmPanel');e.innerHTML='';const shell=this.el('div',{className:'panel-shell'}),head=this.el('div',{className:'panel-head'});head.append(this.el('h1',{},title));head.append(this.el('button',{onclick:()=>this.closePanel()},gameRunning?'← В ИГРУ':'← МЕНЮ'));shell.append(head);e.append(shell);showScreen('rmPanel');return shell;},
 closePanel(){if(gameRunning){if(comp?.started&&this.panelPausedAt)comp.startTime+=performance.now()-this.panelPausedAt;this.panelPausedAt=0;showScreen('game');gamePaused=false;window.clearDrivingControls?.();keys={};}else this.home();},
 home(){this.panelPausedAt=0;if(gameRunning){leaveGame();return;}showScreen('mainMenu');this.balance();},
 async tracks(mode,challenger=null){const root=this.panel(mode==='legal'?'ЛЕГАЛ / ВЫБОР ТРАССЫ':'НЕЛЕГАЛ / ГОРОД ЖИВЁТ');const version=this.panelVersion;const toolbar=this.el('div',{className:'toolbar'});if(mode==='legal'){const select=this.el('select');select.append(this.el('option',{value:'forward'},'Прямое направление'),this.el('option',{value:'reverse'},'Обратное направление'));select.value=Tracks.direction;select.onchange=()=>{Tracks.direction=select.value;this.tracks(mode,challenger);};toolbar.append(select);}toolbar.append(this.el('span',{className:'muted'},'Локальные результаты сохраняются на этом устройстве'));root.append(toolbar);const grid=this.el('div',{className:'grid track-carousel'});root.append(grid);
  const entries=Object.entries(MAPS).filter(([id,t])=>mode==='legal'?(!t.mode||t.mode==='legal'):(!t.mode||t.mode==='illegal'));
  for(const [id,t] of entries){const tile=this.el('article',{className:'tile'});tile.append(this.el('img',{className:'track-preview',src:t.preview,alt:t.name,loading:'lazy'}),this.el('h2',{},t.name));const best=this.el('p',{},'Рекорд: —');tile.append(best);const btns=this.el('div',{className:'buttons'});const dirAllowed=!!t.route;for(const m of challenger?['tandem']:mode==='legal'?['training','competition']:['illegal'])btns.append(this.el('button',{className:'primary',onclick:()=>challenger?Tandem.start(challenger,id):Game.start(id,m)},m==='tandem'?'ПАРНЫЙ ЗАЕЗД':m==='training'?'ТРЕНИРОВКА':m==='competition'?'СОРЕВНОВАНИЕ':'ЕХАТЬ'));tile.append(btns);grid.append(tile);
   try{if(mode!=='legal'){best.textContent='Свободный дрифт · без рейтинга';continue;}const runs=await Save.list(id,dirAllowed?Tracks.direction:'forward','competition');if(version!==this.panelVersion)return;if(runs.length&&!challenger){best.textContent=`${runs[0].nick} · ${runs[0].score} · ${runs[0].elapsed.toFixed(1)} с`;btns.append(this.el('button',{onclick:()=>Game.start(id,runs[0].mode,runs[0])},'ЛУЧШИЙ GHOST'));}}catch(e){best.textContent='Хранилище результатов недоступно';}
  }
 },
 garage(shop){Pursuit.refresh();const root=this.panel(shop?'АВТОСАЛОН':'ГАРАЖ');if(!shop)root.append(this.el('img',{src:'assets/social/homeboy-'+Save.state.social.outfit+'.webp',className:'garage-homeboy',alt:'Хоумбой — твой персонаж'}),this.el('button',{onclick:()=>Social.open()},'ХОУМБОЙ · ОДЕЖДА'));root.append(this.el('p',{className:'balance'},`${Math.floor(Save.state.money)} ₽ · Выбрана: ${Vehicles.current().name}`));const grid=this.el('div',{className:'grid'});root.append(grid);
  for(const c of CATALOG.cars){const owned=Save.state.owned.includes(c.id),impounded=Save.state.impound[c.id];if(!shop&&!owned)continue;const tile=this.el('article',{className:'tile'}),cv=this.el('canvas',{width:300,height:170});tile.append(cv,this.el('h2',{},c.name+' · '+c.class));Vehicles.preview(cv,c,Save.state.custom[c.id]);const stats=this.el('div',{className:'stats'});for(const [label,key] of [['SPEED','topSpeed'],['ACCEL','acceleration'],['GRIP','grip'],['DRIFT','stability'],['CONTROL','steering'],['BRAKE','brake'],['WEIGHT','weight'],['ANGLE','angle']]){const row=this.el('div',{},label+' ');row.append(this.el('progress',{max:2.6,value:c.stats[key]}));stats.append(row);}tile.append(stats);
   tile.append(this.el('p',{},owned?'В гараже':c.bonus?`${c.price} ₽ · ${Economy.unlocked(c)?'Достижение открыто':'Нужно достижение: '+(Achievements.find(a=>a.car===c.id)?.name||c.name)}`:`${c.price} ₽ · Условие: ${c.unlock.toLocaleString('ru')} DRIFT`));
   const b=this.el('button',{className:'primary',disabled:owned?!!impounded||Save.state.selected===c.id:!Economy.unlocked(c)||Save.state.money<c.price,onclick:()=>{if(owned&&Pursuit.available(c.id)){Save.state.selected=c.id;Save.persist();}else Economy.buy(c.id);this.garage(shop);}},owned?(Save.state.selected===c.id?'ВЫБРАНА':'ВЫБРАТЬ'):'КУПИТЬ');tile.append(b);
   if(impounded){tile.append(this.el('p',{},'ШТРАФСТОЯНКА · до '+new Date(impounded.until).toLocaleTimeString('ru')+' · возврат '+impounded.cost+' ₽'),this.el('button',{disabled:Save.state.money<impounded.cost,onclick:()=>{Pursuit.recover(c.id);this.garage(shop);}},'ВЕРНУТЬ МАШИНУ'));}
   if(!shop&&Save.state.selected===c.id){for(const [kind,label,options] of [['paint','Окраска · 300 ₽',['Заводская','Красный металлик']],['rims','Диски · 500 ₽',['Заводские / серебристые','Бронзовые 6-spoke']],['aero','Обвес · 1000 ₽',['Заводской','Track: расширения и сплиттер']]]){const row=this.el('label',{className:'toolbar'},label),sel=this.el('select',{ariaLabel:label});if(['baseline','rare','silvia'].includes(c.id)&&kind==='paint')options.push('Синий металлик','Лесной зелёный');if(['baseline','rare','silvia'].includes(c.id)&&kind==='rims'&&(Save.state.custom[c.id]?.paint||0)>=2)options.push('Белые 5-spoke','Чёрная сетка');options.forEach((text,i)=>sel.append(this.el('option',{value:String(i)},text)));sel.value=Save.state.custom[c.id]?.[kind]||0;sel.onchange=()=>{if(!Economy.custom(kind,Number(sel.value)))this.toast('Недостаточно денег или несовместимые опции: белые и чёрные диски доступны с синим и зелёным кузовом');this.garage(false);};row.append(sel);tile.append(row);}tile.append(this.el('p',{},'Опции сочетаются независимо. Повторная установка купленной детали бесплатна.'));}
   grid.append(tile);
  }
 },
 achievements(){const root=this.panel('ДОСТИЖЕНИЯ');const g=this.el('div',{className:'grid'});root.append(g);for(const a of Achievements){const t=this.el('article',{className:'tile'});t.append(this.el('h2',{},a.name),this.el('p',{},`${Math.min(a.goal,Math.floor(a.value(Save.state)))} / ${a.goal} · +${a.reward} ₽`),this.el('progress',{max:a.goal,value:a.value(Save.state)}),this.el('p',{},Save.state.achievements.includes(a.id)?'ПОЛУЧЕНО':'В ПРОЦЕССЕ'));g.append(t);}},
 async leaderboard(id='isakiy',mode='competition',direction=Tracks.direction){const root=this.panel('РЕЙТИНГ / GHOST');const version=this.panelVersion;const bar=this.el('div',{className:'toolbar'}),select=this.el('select'),m=this.el('select'),d=this.el('select');for(const [i,t] of Object.entries(MAPS).filter(([,t])=>t.mode==='legal'))select.append(this.el('option',{value:i},t.name));select.value=id;for(const [i,n] of [['competition','Соревнование']])m.append(this.el('option',{value:i},n));m.value=mode;for(const [i,n] of [['forward','Прямое'],['reverse','Обратное']])d.append(this.el('option',{value:i},n));d.value=direction;select.onchange=m.onchange=d.onchange=()=>this.leaderboard(select.value,m.value,d.value);bar.append(select,m,d);root.append(bar);
  try{const runs=await Save.list(id,direction,mode);if(version!==this.panelVersion)return;if(!runs.length){root.append(this.el('p',{className:'muted'},'Пока нет сохранённых заездов. Завершите заезд и сохраните результат с ником.'));return;}const table=this.el('table');table.innerHTML='<thead><tr><th>#</th><th>НИК</th><th>ОЧКИ</th><th>ВРЕМЯ</th><th>GHOST</th></tr></thead>';const body=this.el('tbody');runs.forEach((r,i)=>{const tr=this.el('tr');for(const s of [i+1,r.nick,r.score,r.elapsed.toFixed(1)+' с'])tr.append(this.el('td',{},s));const td=this.el('td');td.append(this.el('button',{onclick:()=>{Tracks.direction=r.direction;Game.start(id,r.mode,r);}},'ЕХАТЬ ПРОТИВ GHOST'));tr.append(td);body.append(tr);});table.append(body);root.append(table);}catch(e){root.append(this.el('p',{},'Не удалось открыть результаты: '+e.message));}
 },
 music(){const tracks=Economy.audioTracks(),a=Economy.audio(),root=this.panel('МУЗЫКА · '+a.level.toUpperCase()+' · '+tracks.length+' ТРЕКОВ');if(!tracks.length){root.append(this.el('p',{},a.level==='none'?'Купи аудиосистему в LOUD SOUND на карте ГОРОД.':'Аудиосистема куплена. Установи её в AR DRIVE за 10 000 ₽.'));return;}const bar=this.el('div',{className:'toolbar'});for(const [s,f] of [['◀',()=>AudioPlayer.next(-1)],['PLAY',()=>AudioPlayer.setMusic(true)],['PAUSE',()=>AudioPlayer.setMusic(false)],['▶',()=>AudioPlayer.next(1)],['RANDOM',()=>AudioPlayer.random()]])bar.append(this.el('button',{onclick:f},s));const select=this.el('select',{id:'trackSelect'});tracks.forEach(i=>select.append(this.el('option',{value:i},'Трек '+(i+1))));select.value=tracks.includes(Save.state.settings.track)?Save.state.settings.track:tracks[0];select.onchange=()=>AudioPlayer.select(Number(select.value));bar.append(select);root.append(bar);const range=this.el('input',{type:'range',min:0,max:1,step:.05,value:Save.state.settings.volume});range.oninput=()=>{Save.state.settings.volume=+range.value;AudioPlayer.music.volume=Save.state.settings.master===false?0:+range.value;Save.persist();};root.append(this.el('p',{},'Громкость музыки'),range);},
 renderMusic(){const s=document.getElementById('trackSelect');if(s)s.value=Save.state.settings.track;},
 settings(){const root=this.panel('НАСТРОЙКИ');root.append(this.el('button',{onclick:()=>this.music()},'МУЗЫКА · ПЛЕЕР И АВТОЗВУК'),this.el('p',{className:'muted'},'Музыка: купи STANDARD или PRO в LOUD SOUND, затем установи систему в AR DRIVE. Оба места находятся в Городе. В плеере выбирай трек, PLAY, PAUSE или RANDOM.'));const s=Save.state.settings;const master=this.el('input',{type:'checkbox',checked:s.master!==false});master.onchange=()=>{s.master=master.checked;Save.persist();AudioManager.changed();};const masterRow=this.el('p');masterRow.append(master,document.createTextNode(' MASTER · Все звуки'));root.append(masterRow);const quality=this.el('select',{ariaLabel:'Производительность'});for(const [v,n] of [['auto','Авто'],['low','Экономный режим · 30 FPS'],['high','Плавный режим · 60 FPS']])quality.append(this.el('option',{value:v},n));quality.value=s.quality||'auto';quality.onchange=()=>{s.quality=quality.value;Save.persist();};root.append(this.el('p',{},'Производительность'),quality);for(const [label,value,fn] of [['MUSIC',s.music,v=>AudioPlayer.setMusic(v)],...['engine','drift','effects'].map((k,i)=>[['ДВИГАТЕЛЬ','ДРИФТ','ЭФФЕКТЫ'][i],s[k]!==false,v=>{s[k]=v;Save.persist();AudioManager.changed();}]),['Обучение',Save.state.tutorial,v=>{Save.state.tutorial=v;Save.persist();}]]){const row=this.el('p'),input=this.el('input',{type:'checkbox',checked:value});input.onchange=()=>fn(input.checked);if(label==='MUSIC'&&!Economy.audioTracks().length){input.checked=false;input.disabled=true;}row.append(input,document.createTextNode(' '+label));root.append(row);}const bar=this.el('div',{className:'toolbar'});bar.append(this.el('span',{},'Масштаб камеры'));for(const z of [.5,1,2])bar.append(this.el('button',{onclick:()=>{s.zoom=z;setMobileCameraMultiplier(z);Save.persist();}},z+'×'));root.append(bar,this.el('button',{onclick:()=>this.tutorial()},'ПРОЙТИ ОБУЧЕНИЕ'),this.el('p',{className:'muted'},'Результаты и прогресс локальны. Экспорт включает повторы заездов.'),this.el('button',{onclick:async()=>{try{const data=await Save.export();const url=URL.createObjectURL(new Blob([JSON.stringify(data)],{type:'application/json'}));const a=this.el('a',{href:url,download:'raremasters-save.json'});a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){this.toast(e.message);}}},'ЭКСПОРТ СОХРАНЕНИЯ'));
 },
 dialog(character,text,buttons,policeScene=false){if(character===0||character===5)character={name:CATALOG.characters[character],image:'assets/social/'+(character===0?'artak':'osman')+'.webp'};const token=++this.dialogToken,wasPaused=gamePaused,pausedAt=performance.now();gamePaused=true;AudioPlayer.stopGame();window.clearDrivingControls?.();keys={};const e=document.getElementById('rmDialog');e.innerHTML='';const box=this.el('div',{className:'dialog-box'}),body=this.el('div',{className:'dialog-body'}),portrait=this.el('div',{className:'portrait'});if(typeof character==='object'){portrait.style.backgroundImage=`url('${character.image}')`;portrait.style.backgroundSize='contain';portrait.style.backgroundRepeat='no-repeat';}else portrait.style.backgroundPosition=`${(character%3)*50}% ${Math.floor(character/3)*50}%`;const content=this.el('div');content.append(this.el('div',{className:'dialog-name'},typeof character==='object'?character.name:CATALOG.characters[character]),this.el('p',{},text));body.append(portrait,content);box.append(body);if(policeScene){const scene=this.el('div',{className:'police-scene'}),cv=this.el('canvas',{width:250,height:130});scene.append(cv);box.append(scene);Vehicles.policePreview(cv,Math.max(1,World.heat));}const btns=this.el('div',{className:'buttons'});for(const [label,fn] of buttons)btns.append(this.el('button',{onclick:()=>{e.style.display='none';if(comp?.started&&!wasPaused)comp.startTime+=performance.now()-pausedAt;gamePaused=wasPaused;fn();}},label));box.append(btns);e.append(box);e.style.display='flex';},
 tutorial(){Guide.start();},
 pause(){if(!gameRunning)return;this.dialog(6,'Пауза. Машина и запись заезда остановлены.',[['ПРОДОЛЖИТЬ',()=>{}],['В МЕНЮ',()=>leaveGame()]]);},
 minimap(){if(this.miniAt&&performance.now()-this.miniAt<100)return;this.miniAt=performance.now();const c=document.getElementById('miniMap'),g=c.getContext('2d');g.clearRect(0,0,c.width,c.height);if(!car)return;const z=Math.min(c.width/W,c.height/H),ox=(c.width-W*z)/2,oy=(c.height-H*z)/2;if(this.miniSource!==mapImg){this.miniSource=mapImg;this.miniBackground=document.createElement('canvas');this.miniBackground.width=c.width;this.miniBackground.height=c.height;this.miniBackground.getContext('2d').drawImage(mapImg,ox,oy,W*z,H*z);}g.drawImage(this.miniBackground,0,0);g.fillStyle='#ffdf5c';g.beginPath();g.arc(ox+car.x*z,oy+car.y*z,4,0,7);g.fill();if(selectedMode==='city'){if(City.destination){g.strokeStyle='#ffda42';g.lineWidth=2;g.beginPath();g.moveTo(ox+car.x*z,oy+car.y*z);g.lineTo(ox+City.destination.x*z,oy+City.destination.y*z);g.stroke();}for(const p of City.places){g.fillStyle=City.destination===p?'#ffda42':'#68e8cf';g.fillRect(ox+p.x*z-3,oy+p.y*z-3,6,6);}}if(selectedMode==='competition'&&markers.lines[1]){g.fillStyle='#ff6079';g.fillRect(ox+markers.lines[1].cx*z-2,oy+markers.lines[1].cy*z-2,4,4);}}
};
UI.init();window.UI=UI;

